import type { AppProps } from "next/app";
import { extendTheme } from "@chakra-ui/react";
import { ChakraProvider } from "@chakra-ui/react";
import Fonts from "../styles/fonts/font";

const Link = {
  variants: {
    icTopa: {
      textDecoration: "none",
      WebkitTransition: "all .25s ease",
      transition: "all .25s ease",
      _hover: {
        color: "theme.200",
      },
    },
  },
};
const Heading = {
  variants: {
    icTopH1: {
      color: "white",
      fontSize: "4.1em",
      lineHeight: 1.2,
    },
  },
};
const Text = {
  variants: {
    icTopP: {
      color: "white",
      fontSize: "1.6em",
      margin: "0",
      letterSpacing: "0.01em",
    },
  },
};
const theme = extendTheme({
  colors: {
    background: {
      100: "#1b2229",
      200: "#222",
    },
    theme: {
      100: "#05d1c4",
      200: "#04aca1",
    },
    gry: {
      100: "#e2e2e2",
      200: "#cfcfcf",
    },
  },
  styles: {
    global: (props) => ({
      "html, body": {
        margin: 0,
        padding: 0,
        height: "100%",
      },
      body: {
        color: "background.100",
        fontFamily: '"SFProDisplay", sans-serif',
        fontSize: "14px",
        lineHeight: 1.42857143,
        paddingTop: "55px",
      },
      "*": { WebkitBoxSizing: "border-box", boxSizing: "border-box" },
      "body, html": { margin: "0", padding: "0", height: "100%" },
      ".inner-body": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxOrient: "vertical",
        WebkitBoxDirection: "normal",
        msFlexDirection: "column",
        flexDirection: "column",
      },
      ".inner-body header": { height: "auto" },
      ".inner-body main": {
        WebkitBoxFlex: "1",
        msFlex: "1 0 auto",
        flex: "1 0 auto",
        width: "100%",
      },
      a: { color: "theme.100" },
      p: { margin: "0 0 10px" },
      ul: { margin: "0", padding: "0" },
      "ul li": { listStyleType: "none" },
      ".container, .container-fluid": {
        position: "relative",
        paddingRight: "15px",
        paddingLeft: "15px",
        marginRight: "auto",
        marginLeft: "auto",
      },
      ".container": { maxWidth: "1230px" },
      ".img-responsive": { display: "block", maxWidth: "100%", height: "auto" },
      ".text-center": { textAlign: "center" },
      ".btn": { cursor: "pointer", display: "inline-block", outline: "none" },
      ".grey-btn": { background: "gry.100", color: "background.200" },
      ".grey-btn:hover": { background: "gry.200" },
      ".green-btn": { background: "theme.100", color: "#fff" },
      ".green-btn:hover": { background: "#04b8ad" },
      ".green-btn:disabled": { background: "#06f6e7" },
      ".red-btn": { background: "#E94241", color: "#fff" },
      ".red-btn:hover": { background: "#e5201f", color: "#fff" },
      ".red-btn:disabled": { background: "#ed6463" },
      ".green-text": { color: "theme.100" },
      ".infographic-wrapper": { position: "relative", overflow: "hidden" },
      ".infographic-wrapper section:nth-of-type(even)": {
        background: "#fff url(assets/img/cross-bg.svg)",
        backgroundSize: "175px",
        padding: "30px 0 40px",
      },
      ".infographic-wrapper section:nth-of-type(even) .container": {
        WebkitBoxOrient: "unset",
        WebkitBoxDirection: "unset",
        msFlexDirection: "unset",
        flexDirection: "unset",
      },
      ".infographic-wrapper .container": { msFlexWrap: "wrap", flexWrap: "wrap" },
      ".infographic-wrapper h1,\n.infographic-wrapper h2,\n.infographic-wrapper h3": {
        color: "theme.100",
        marginTop: "0",
      },
      ".infographic-wrapper h1 span,\n.infographic-wrapper h2 span,\n.infographic-wrapper h3 span": {
        color: "#E94241",
        fontSize: "1.625em",
        fontWeight: 400,
      },
      ".video-dating": {
        background: "background.100",
        color: "#fff",
        padding: "45px 0 105px",
      },
      ".video-dating .container": { msFlexWrap: "wrap", flexWrap: "wrap" },
      ".vd-title": { width: "100%", marginTop: "5%" },
      ".vd-title h1": {
        fontSize: "2.75em",
        fontFamily: '"SFProRounded", sans-serif',
        margin: "0",
      },
      ".vd-title h1:before": {
        content: "''",
        background: "url(assets/img/logo-rounded.svg) no-repeat",
        display: "inline-block",
        marginRight: "0.4em",
        marginLeft: "0.9em",
        verticalAlign: "-0.25em",
        height: "1.2em",
        width: "4.4em",
      },
      ".vd-title strong": {
        color: "#E94241",
        fontSize: "4.5em",
        fontWeight: 500,
        lineHeight: 1.2,
        letterSpacing: "0.02em",
      },
      ".vd-title strong:before": {
        content: "'\\e804'",
        display: "inline-block",
        fontFamily: "'CamgoIcons'",
        fontSize: "0.5em",
        marginRight: "0.4em",
        marginLeft: "-0.5em",
        WebkitTransform: "rotate(-12deg)",
        transform: "rotate(-12deg)",
        verticalAlign: "0.3em",
      },
      ".vd-wrap": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        width: "100%",
      },
      ".vdw-score": {
        opacity: 0,
        position: "relative",
        textAlign: "center",
        width: "50%",
        zIndex: 1,
      },
      ".vdw-score strong": {
        color: "theme.100",
        fontFamily: '"SFProRounded", sans-serif',
        fontSize: "4.2em",
        letterSpacing: "0.075em",
        lineHeight: 0.9,
        textShadow: "0.065em 0.065em 0 #145455",
        position: "relative",
        zIndex: 1,
      },
      ".vdw-score p": {
        fontSize: "1.4em",
        letterSpacing: "0.02em",
        margin: "0.5em 0 0",
        position: "relative",
        zIndex: 1,
      },
      ".vdw-list": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        WebkitBoxOrient: "vertical",
        WebkitBoxDirection: "normal",
        msFlexDirection: "column",
        flexDirection: "column",
        position: "relative",
        width: "50%",
        zIndex: 1,
      },
      ".vdw-list li": {
        fontSize: "1.5em",
        marginBottom: "0.8em",
        minWidth: "12em",
        opacity: 0,
      },
      ".vdw-list li:before": {
        content: "''",
        backgroundRepeat: "no-repeat",
        display: "inline-block",
        marginRight: "0.5em",
        verticalAlign: "-0.8em",
        height: "2.3em",
        width: "2.3em",
      },
      ".vdw-list li:nth-of-type(1)::before": {
        backgroundImage: "url(assets/img/icon-1.svg)",
      },
      ".vdw-list li:nth-of-type(2)::before": {
        backgroundImage: "url(assets/img/icon-2.svg)",
      },
      ".vdw-list li:nth-of-type(3)::before": {
        backgroundImage: "url(assets/img/icon-3.svg)",
      },
      ".vdw-list li:nth-of-type(4)::before": {
        backgroundImage: "url(assets/img/icon-4.svg)",
      },
      ".vdw-list li:nth-of-type(5)::before": {
        backgroundImage: "url(assets/img/icon-5.svg)",
      },
      ".vdw-list li span": { color: "theme.100", marginLeft: "0.25em" },
      "header ": {
        backgroundColor: "theme.100",
        position: "fixed",
        top: "0",
        height: "55px",
        width: "100%",
        zIndex: 100002,
      },
      "header .container-fluid": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxPack: "justify",
        msFlexPack: "justify",
        justifyContent: "space-between",
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
        padding: "0 20px",
      },
      ".head-logo": { marginRight: "auto" },
      ".head-logo a": {
        display: "inline-block",
        margin: "3px 0 0",
        width: "150px",
      },
      "@media only screen and (min-width: 1500px)": {
        ".home-welcone.container": { maxWidth: "1230px!important" },
        ".app-intro": { fontSize: "15px!important" },
        ".intro-content:before": { height: "710px!important" },
        ".ic-form": { padding: "0 1em" },
        ".ic-start": { marginTop: "1.75em" },
        ".ic-start .ics-btn": { marginTop: "2em" },
        ".ic-interests .ici-available": { minHeight: "6em" },
        ".ic-cont": { fontSize: "15px" },
      },
      "@media only screen and (min-width: 1833px)": {
        ".ic-cont,.app-intro": { fontSize: "16px" },
        ".intro-content:before": { height: "780px" },
        ".ic-top": { marginBottom: "2.5em" },
        ".ic-start": { marginTop: "2em" },
        ".ic-start .ics-btn": { marginTop: "3em" },
        ".ic-interests": { marginTop: "2.5em" },
      },
      ".ft-img": { width: "540px" },
      ".ft-img:not(.bounceInLeft) img": { display: "none" },
      ".ft-content": {
        WebkitBoxFlex: "1",
        msFlex: "1",
        flex: 1,
        paddingLeft: "4.5em",
      },
      ".ft-content h2": {
        fontSize: "2.7em",
        paddingRight: "0.5em",
        lineHeight: 1.2,
        marginBottom: "0.3em",
        fontWight: 600,
      },
      ".ft-content h2 span": { display: "block" },
      ".ft-content p": { fontSize: "1.45em" },
      ".iw-features": { background: "theme.100", padding: "0" },
      ".iw-features p": {
        fontSize: "1.4em",
        maxWidth: "90%",
        margin: "0.2em 5% 1em",
      },
      ".iwf-wrap": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        padding: "0.25em 0",
        width: "100%",
      },
      ".iwf-item": {
        minHeight: "20em",
        position: "relative",
        padding: "2em 0 0",
        width: "50%",
      },
      ".iwf-item+.iwf-item img": { marginLeft: "0.5em" },
      ".iwf-item+.iwf-item .iwf-cont": { left: "52.5%" },
      ".iwf-item>div": { position: "relative", zIndex: 1 },
      ".iwf-item:after": {
        content: "''",
        background: "url(/assets/img/dots-bg-black.svg) no-repeat",
        position: "absolute",
        top: "3%",
        left: "2%",
        height: "100%",
        width: "72.5%",
        opacity: 0.09,
        WebkitTransform: "rotate(10deg)",
        transform: "rotate(10deg)",
        zIndex: 0,
      },
      ".iwf-item img": {
        position: "relative",
        marginLeft: "2em",
        height: "100%",
        width: "80%",
        zIndex: 1,
      },
      ".iwf-item .iwf-cont": {
        position: "absolute",
        top: "50%",
        right: "5%",
        left: "50%",
        WebkitTransform: "translate(7%, -50%)",
        transform: "translate(7%, -50%)",
        zIndex: 1,
      },
      ".iwf-item .iwf-cont h4": {
        background: "#fff",
        WebkitBoxShadow: "-10px 0 0 #ffffff, 10px 0 0 #ffffff",
        boxShadow: "-10px 0 0 #ffffff, 10px 0 0 #ffffff",
        color: "#E94241",
        display: "inline",
        fontSize: "2.1em",
        fontFamily: '"SFProRounded", sans-serif',
        letterSpacing: "0.02em",
        lineHeight: 1.25,
        padding: "0.1em 0",
        textShadow: "1px 0px",
      },
      ".gender-selected label": {
        display: "flex!important",
        alignItems: "center",
      },
      ".interest-based .container": { position: "static" },
      ".interest-based .container:after": {
        content: "''",
        background: "url(/assets/img/boy.svg) no-repeat",
        position: "absolute",
        bottom: "-2px",
        left: "1%",
        height: "9em",
        width: "7em",
      },
      ".interest-based h3": {
        fontSize: "2.7em",
        letterSpacing: "0.005em",
        lineHeight: 1,
        margin: "0",
        width: "100%",
      },
      ".interest-based h3 span": { fontSize: "1.45em" },
      ".interest-based p": {
        color: "#696e73",
        fontSize: "1.05em",
        maxWidth: "76%",
        margin: "2em 12% 0",
      },
      ".ib-wrap": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        width: "100%",
      },
      ".ib-wrap>div": { padding: "0 2em", position: "relative", width: "33%" },

      ".ib-wrap>div h4": { fontSize: "2em", margin: "-0.5em 0 0", opacity: 0 },
      ".head-logo img": { width: "100%", height: "auto" },
      ".head-mnu": {
        background: "#fff",
        borderLeft: "1px solid background.100",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxOrient: "vertical",
        WebkitBoxDirection: "normal",
        msFlexDirection: "column",
        flexDirection: "column",
        msFlexWrap: "wrap",
        flexWrap: "wrap",
        padding: "55px 20px 20px",
        position: "fixed",
        right: "-300px",
        top: "0",
        WebkitTransition: "right 0.5s ease",
        transition: "right 0.5s ease",
        height: "100%",
        width: "300px",
      },
      ".head-mnu:before": {
        content: '""',
        background: "#1b2229 url(assets/img/logo-white.svg) center/50% no-repeat",
        width: "100%",
        height: "55px",
        display: "block",
        position: "absolute",
        left: "0",
        top: "0",
      },
      ".head-mnu li": { display: "block", textAlign: "center" },
      ".head-mnu li a": {
        color: "background.100",
        display: "block",
        fontSize: "17px",
        fontWeight: 600,
        margin: "0",
        padding: "17px 0",
        textDecoration: "none",
        WebkitTransition: "all 0.25s ease",
        transition: "all 0.25s ease",
      },
      ".head-mnu li a:hover": { color: "theme.100" },
      ".head-mnu li:last-child": {
        WebkitBoxFlex: "1",
        msFlex: "auto",
        flex: "auto",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        borderTop: "0",
      },
      "body:not(.home-body) .head-mnu li:last-child": { display: "none" },
      ".head-mnu li:last-child p": {
        cursor: "pointer",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        fontSize: "15px",
        margin: "auto 0 0",
      },
      ".head-mnu li:last-child p:hover": { color: "theme.100" },
      ".head-mnu li:last-child p em": { fontSize: "1.25em", marginRight: "5px" },
      ".head-mnu li .get-plus": {
        background: "theme.100",
        borderRadius: "50px",
        color: "#fff",
        cursor: "pointer",
        display: "none",
        fontSize: "17px",
        fontWeight: 600,
        margin: "18px 0 0",
      },
      ".head-mnu li .get-plus>*": {
        display: "inline-block",
        letterSpacing: "1px",
        padding: "0.3em 0.75em",
      },
      ".head-mnu li .get-plus span": {
        background: "background.100",
        borderRadius: "50px",
        color: "theme.100",
      },
      ".head-mnu li .get-plus em": {
        fontStyle: "normal",
        fontWeight: "normal",
        padding: "0.3em 0.75em 0.3em 0.3em",
        textShadow: "0 0",
      },
      ".head-mnu li .get-plus:hover": {
        WebkitTransform: "scale(1.05)",
        transform: "scale(1.05)",
        WebkitTransition: "all .15s linear",
        transition: "all .15s linear",
      },
      ".rlt-vip-member .head-mnu li .get-plus": { display: "none !important" },
      ".head-mnu li+li": { borderTop: "1px solid #dadada" },
      ".nav-open .head-mnu": { right: "0" },
      ".page-overlay": {
        background: "rgba(27, 34, 41, 0.8)",
        position: "fixed",
        top: "0",
        left: "0",
        opacity: 0,
        visibility: "hidden",
        WebkitTransition: "all 0.3s ease",
        transition: "all 0.3s ease",
        height: "100%",
        width: "100%",
        zIndex: 10,
      },
      ".head-count": {
        color: "#145455",
        fontSize: "14px",
        fontWeight: 600,
        marginRight: "20px",
        textShadow: "0 0 0",
        display: "flex",
        alignItems: "center",
      },
      ".head-count em": {
        fontSize: "1.4em",
        marginRight: "3px",
        verticalAlign: "baseline",
      },
      ".head-count span": { fontSize: "1.3em" },
      ".head-toggle": {
        display: "block",
        cursor: "pointer",
        position: "relative",
        WebkitTransform: "rotate(0deg)",
        transform: "rotate(0deg)",
        WebkitTransition: "0.5s ease-in-out",
        transition: "0.5s ease-in-out",
        height: "26px",
        width: "36px",
      },
      ".head-toggle span": {
        background: "#145455",
        borderRadius: "15px",
        display: "block",
        position: "absolute",
        left: "0",
        opacity: 1,
        WebkitTransform: "rotate(0deg)",
        transform: "rotate(0deg)",
        WebkitTransition: "0.25s ease-in-out",
        transition: "0.25s ease-in-out",
        height: "4px",
        width: "100%",
      },
      ".head-toggle span:nth-of-type(1)": { top: "0px" },
      ".head-toggle span:nth-of-type(2), .head-toggle span:nth-of-type(3)": {
        top: "11px",
      },
      ".head-toggle span:nth-of-type(4)": { top: "22px" },
      ".nav-open .head-toggle span:nth-of-type(4), .nav-open .head-toggle span:nth-of-type(1)": {
        top: "11px",
        width: "0%",
        left: "50%",
      },
      ".nav-open .head-toggle span:nth-of-type(2)": {
        WebkitTransform: "rotate(45deg)",
        transform: "rotate(45deg)",
      },
      ".nav-open .head-toggle span:nth-of-type(3)": {
        WebkitTransform: "rotate(-45deg)",
        transform: "rotate(-45deg)",
      },
      ".app-intro, header": {
        right: "0",
        WebkitTransition: "right 0.5s ease",
        transition: "right 0.5s ease",
      },
      ".app-intro": {
        background: "background.100",
        fontSize: "12px",
        fontFamily: '"SFProRounded", sans-serif',
        position: "relative",
        overflow: "hidden",
        height: "100%",
        paddingTop: "7.1%",
      },
      ".home-welcone": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
        height: "100%",
        opacity: 0,
        paddingBottom: "7%",
      },
      ".intro-content": {
        maxWidth: "38.5em",
        paddingBottom: "15px",
        WebkitTransition: "opacity 0.5s ease",
        transition: "opacity 0.5s ease",
        textAlign: "center",
        width: "100%",
      },
      ".intro-content *::-moz-selection": { background: "none" },
      ".intro-content *::selection": { background: "none" },
      ".ic-form": { position: "relative", zIndex: 10 },
      ".ic-top": {
        marginBottom: "2em",
        position: "relative",
        whiteSpace: "nowrap",
        zIndex: 1,
      },
      ".ic-top strong": { color: "#fff", fontSize: "4.1em", lineHeight: 1.2 },
      ".ic-top p": {
        color: "#fff",
        fontSize: "1.6em",
        margin: "0",
        letterSpacing: "0.01em",
      },
      ".ic-top p a": {
        textDecoration: "none",
        WebkitTransition: "all .25s ease",
        transition: "all .25s ease",
      },
      ".ic-top p a:hover": { color: "theme.200" },
      ".ic-select": {
        color: "background.100",
        fontSize: "1.8em",
        fontWeight: 600,
        margin: "0 auto",
        position: "relative",
        textAlign: "left",
        zIndex: 10,
      },
      ".ic-select.active>span": {
        borderRadius: "0.4em 0.4em 0 0",
        WebkitTransition: "none",
        transition: "none",
      },
      ".ic-select>span": {
        background: "#fff",
        borderRadius: "0.4em",
        cursor: "pointer",
        display: "inline-block",
        padding: "0.6em 1em",
        WebkitTransition: "border-radius 0.25s ease",
        transition: "border-radius 0.25s ease",
        WebkitTransitionDelay: "0.325s",
        transitionDelay: "0.325s",
        width: "100%",
      },
      ".ic-select>span:hover": { color: "#1dc4ba" },
      ".ic-select>span:after": {
        content: '"\\E809"',
        color: "theme.100",
        fontSize: "0.75em",
        fontFamily: "CamgoIcons",
        position: "absolute",
        top: "55%",
        right: "5%",
        WebkitTransform: "translateY(-50%)",
        transform: "translateY(-50%)",
      },
      ".ic-select>span em": { fontWeight: "bold", margin: "0 0.65em" },
      ".ic-select ul": {
        background: "#fff",
        borderRadius: "0 0 0.4em 0.4em",
        display: "none",
        margin: "0",
        padding: "0.5em 1em 0",
        position: "absolute",
        width: "100%",
      },
      ".ic-select ul li": { listStyleType: "none" },
      ".ic-select ul li input": { display: "none" },
      ".ic-select ul li label": {
        borderTop: "1px solid #dfe7ed",
        color: "background.100",
        cursor: "pointer",
        display: "block",
        marginBottom: "7px",
        fontSize: "0.9em",
        padding: "10px 5px",
        whiteSpace: "nowrap",
      },
      ".ic-select ul li label:hover": { color: "theme.100" },
      ".ic-select ul li label em": { margin: "0 0.25em" },
      ".ic-start": { marginTop: "1.5em" },
      ".ic-start strong": {
        color: "#fff",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        fontSize: "2em",
        letterSpacing: "0.045em",
        textTransform: "uppercase",
        whiteSpace: "nowrap",
      },
      ".ic-start strong em": {
        fontSize: "0.85em",
        msFlexItemAlign: "center",
        msGridRowAlign: "center",
        alignSelf: "center",
        verticalAlign: "sub",
      },
      ".ic-start strong em:after,.ic-start strong em:before": {
        display: "block",
        lineHeight: 0.25,
        position: "relative",
      },
      ".ic-start strong em:before": { opacity: 0.5, top: "0" },
      ".ic-start strong em:after": { content: '"\\E809"', top: "0.3em" },
      ".ic-start strong em:first-of-type": { marginRight: "1.5em" },
      ".ic-start strong em:last-child": { marginLeft: "1.5em" },
      ".ic-start strong.animate em:after,.ic-start strong.animate em:before": {
        WebkitAnimation: "arrow-down 1s linear infinite",
        animation: "arrow-down 1s linear infinite",
      },
      ".ic-start strong.animate em:after": {
        WebkitAnimationDelay: "0.2s",
        animationDelay: "0.2s",
      },
      ".ic-start .ics-btn": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        marginTop: "1.75em",
      },
      ".ic-start .ics-btn p": {
        color: "#fff",
        fontSize: "2em",
        fontWeight: 800,
        margin: "0 1em",
      },
      ".ic-start .ics-btn .btn": {
        borderRadius: "0.35em",
        color: "background.100",
        fontSize: "2.1em",
        fontWeight: 600,
        padding: "0.435em 20px",
        textAlign: "center",
        width: "50%",
      },
      ".ic-cont": {
        color: "#fff",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        marginTop: "2.35em",
        textAlign: "left",
        position: "relative",
      },
      ".ic-cont input": { position: "absolute", visibility: "hidden", zIndex: -1 },
      ".ic-cont input:checked+label:after": {
        WebkitTransform: "scale(1)",
        transform: "scale(1)",
      },
      ".ic-cont input:checked+label:before": { background: "theme.100" },
      ".ic-cont label": {
        cursor: "pointer",
        fontSize: "1.05em",
        fontWeight: 400,
        margin: "0",
        letterSpacing: "0.0175em",
        lineHeight: 1.45,
        paddingLeft: "2em",
        position: "relative",
        textAlign: "center",
        zIndex: 2,
      },
      ".ic-cont label a": {
        color: "#fff",
        WebkitTransition: "color .25s ease",
        transition: "color .25s ease",
      },
      ".ic-cont label a:hover": { color: "theme.100" },
      ".ic-cont label:before,.ic-cont label:after": {
        content: '""',
        position: "absolute",
      },
      ".ic-cont label:before": {
        background: "#fff",
        borderRadius: "0.3em",
        cursor: "pointer",
        left: "0",
        top: "0.085em",
        height: "1.26em",
        width: "1.26em",
      },
      ".ic-cont label:after": {
        content: '"\\E802"',
        fontSize: "1.15em",
        fontFamily: "CamgoIcons",
        fontWeight: "bold",
        lineHeight: 0,
        top: "0.5em",
        left: "0.1em",
        WebkitTransition: "-webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
        transition: [
          "-webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
          "transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
          "transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7), -webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
        ],
        WebkitTransform: "scale(0)",
        transform: "scale(0)",
      },
      ".icc-error": {
        background: "#E94241",
        borderRadius: "3px",
        color: "#fff",
        fontSize: "14px",
        opacity: 0,
        padding: "4px 8px",
        position: "absolute",
        top: "-5px",
        left: "0px",
      },
      ".icc-error:after": {
        content: '""',
        border: "6px solid transparent",
        borderTop: "6px solid #E94241",
        position: "absolute",
        bottom: "-12px",
        left: "6px",
      },
      ".error .icc-error": {
        WebkitTransform: "translateY(-100%)",
        transform: "translateY(-100%)",
        opacity: 1,
      },
      ".ic-interests": { marginTop: "2em", position: "relative", zIndex: 2 },
      ".ic-interests .ici-area": {
        background: "#fff",
        borderRadius: "1em",
        cursor: "text",
        padding: "0.5em 1em",
        textAlign: "left",
        width: "100%",
      },
      ".ic-interests .ici-area form": {
        display: "inline-block",
        minWidth: "20em",
        verticalAlign: "middle",
      },
      ".ic-interests .ici-area form.no-holder": { minWidth: "10em" },
      ".ic-interests .ici-area input": {
        border: "0",
        fontSize: "1.525em",
        marginLeft: "auto",
        outline: "none",
        padding: "0.25em 0.25em 0.25em 0",
        width: "100%",
      },
      ".ic-interests .ici-area input::-ms-clear": { display: "none" },
      ".ic-interests .ici-area input::-moz-selection": { background: "theme.100" },
      ".ic-interests .ici-area input::selection": { background: "theme.100" },
      ".ic-interests .ici-area span": {
        background: "theme.100",
        borderRadius: "6px",
        color: "background.100",
        cursor: "pointer",
        display: "inline-block",
        WebkitBoxFlex: "1",
        msFlex: "1 0 auto",
        flex: "1 0 auto",
        fontSize: "1.2em",
        margin: "0.25em 0.5em 0.25em 0",
        padding: "2px 5px 2px 7px",
        verticalAlign: "middle",
        WebkitTransition: "all 0.25s ease",
        transition: "all 0.25s ease",
      },
      ".ic-interests .ici-area span:hover": { background: "#05c5b8" },
      ".ic-interests .ici-area span:hover em:before,.ic-interests .ici-area span:hover em::after": {
        height: "0.1em",
      },
      ".ic-interests .ici-area span em": {
        cursor: "pointer",
        display: "inline-block",
        marginLeft: "4px",
        position: "relative",
        top: "0",
        left: "0",
      },
      ".ic-interests .ici-area.show-list": {
        borderBottom: "1px solid #d9dbdc",
        borderRadius: "1em 1em 0 0",
      },
      ".ic-interests .ici-available": {
        background: "#fff",
        borderRadius: "0 0 1em 1em",
        display: "none",
        padding: "0.25em 0.5em 0.35em",
        position: "absolute",
        minHeight: "5.25em",
        height: "100%",
        width: "100%",
      },
      ".ic-interests .ici-available::-webkit-scrollbar": { width: "8px" },
      ".ic-interests .ici-available::-webkit-scrollbar-track": {
        background: "#d9dbdc",
        border: "4.5px solid transparent",
        backgroundClip: "content-box",
      },
      ".ic-interests .ici-available::-webkit-scrollbar-thumb": {
        background: "#9a9a9a",
        borderRadius: "10px",
      },
      ".ic-interests .ici-available .icia-list": {
        overflow: "auto",
        height: "100%",
      },
      ".ic-interests .ici-available .icia-list::-webkit-scrollbar": {
        width: "8px",
      },
      ".ic-interests .ici-available .icia-list::-webkit-scrollbar-track": {
        background: "#d9dbdc",
        border: "4.5px solid transparent",
        backgroundClip: "content-box",
      },
      ".ic-interests .ici-available .icia-list::-webkit-scrollbar-thumb": {
        background: "#9a9a9a",
        borderRadius: "10px",
      },
      ".ic-interests .ici-available span": {
        cursor: "pointer",
        display: "block",
        fontSize: "1.1em",
        textAlign: "left",
        padding: "0.15em 0.5em",
        WebkitTransition: "all 0.25s ease",
        transition: "all 0.25s ease",
      },
      ".ic-interests .ici-available span.active,.ic-interests .ici-available span:hover": {
        background: "#f4f4f4",
      },
      ".ic-interests .ici-available span.active::before,.ic-interests .ici-available span:hover::before": {
        color: "background.100",
      },
      ".ic-interests .ici-available span:before": {
        content: '"\\e807"',
        color: "#9a9a9a",
        marginRight: "0.35em",
        fontFamily: "CamgoIcons",
        display: "inline-block",
        verticalAlign: "middle",
      },
      ".learn-more": {
        cursor: "pointer",
        position: "absolute",
        bottom: "5px",
        right: "15px",
        maxWidth: "38em",
        width: "100%",
        textAlign: "center",
      },
      ".learn-more span": {
        color: "#fff",
        display: "inline-block",
        fontSize: "0.75em",
        letterSpacing: "0.1em",
      },
      ".learn-more span:before": {
        content: '"\\E809"',
        fontFamily: "CamgoIcons",
        display: "block",
        textAlign: "center",
        fontSize: "2.5em",
        lineHeight: 1,
      },
      "#app-loading": {
        display: "none",
        background: "background.100",
        position: "absolute",
        top: "0",
        left: "0",
        height: "100%",
        width: "100%",
        zIndex: 101,
      },
      "#app-loading .loader-body": {
        background: "url(/assets/img/logo-icon.svg) center/70% no-repeat",
        WebkitAnimation: "blink 1.25s infinite ease-in-out",
        animation: "blink 1.25s infinite ease-in-out",
        position: "absolute",
        top: "50%",
        left: "50%",
        WebkitTransform: "translate(-50%, -50%)",
        transform: "translate(-50%, -50%)",
        height: "200px",
        width: "200px",
      },
      ".feedback_link": { display: "none !important" },
      "main, footer": { position: "relative", right: "0", opacity: 0 },
      ".nav-open .app-intro, .nav-open main, .nav-open footer, .nav-open header": {
        right: "300px",
      },
      ".nav-open .page-overlay": { visibility: "visible", opacity: 1 },
      ".nav-open .addthis-smartlayers": { display: "none" },
      "main section": {
        fontSize: "18.75px",
        padding: "105px 0",
        position: "relative",
      },
      ".rlt-gender-f .get-plus": { display: "none !important" },
      ".rlt-gender-m .head-mnu li .get-plus, .rlt-gender-c .head-mnu li .get-plus": {
        display: "inline-block",
      },

      "@media only screen and (max-width: 1024px)": {
        ".app-intro": {
          background: "background.100",
          fontSize: "12px",
          fontFamily: '"SFProRounded", sans-serif',
          position: "relative",
          overflow: "hidden",
          height: "100%",
        },
        ".home-welcone": {
          display: ["-webkit-box", "-ms-flexbox", "flex"],
          WebkitBoxAlign: "center",
          msFlexAlign: "center",
          alignItems: "center",
          height: "100%",
          opacity: 0,
        },
        ".intro-content": {
          maxWidth: "38.5em",
          paddingBottom: "15px",
          WebkitTransition: "opacity 0.5s ease",
          transition: "opacity 0.5s ease",
          textAlign: "center",
          width: "100%",
        },
        ".intro-content *::-moz-selection": { background: "none" },
        ".intro-content *::selection": { background: "none" },
        ".ic-form": { position: "relative", zIndex: 10 },
        ".ic-top": {
          marginBottom: "2em",
          position: "relative",
          whiteSpace: "nowrap",
          zIndex: 1,
        },
        ".ic-top strong": { color: "#fff", fontSize: "4.1em", lineHeight: 1.2 },
        ".ic-top p": {
          color: "#fff",
          fontSize: "1.6em",
          margin: "0",
          letterSpacing: "0.01em",
        },
        ".ic-top p a": {
          textDecoration: "none",
          WebkitTransition: "all .25s ease",
          transition: "all .25s ease",
        },
        ".ic-top p a:hover": { color: "theme.200" },
        ".ic-select": {
          color: "background.100",
          fontSize: "1.8em",
          fontWeight: 600,
          margin: "0 auto",
          position: "relative",
          textAlign: "left",
          zIndex: 10,
        },
        ".ic-select.active>span": {
          borderRadius: "0.4em 0.4em 0 0",
          WebkitTransition: "none",
          transition: "none",
        },
        ".ic-select>span": {
          background: "#fff",
          borderRadius: "0.4em",
          cursor: "pointer",
          display: "inline-block",
          padding: "0.6em 1em",
          WebkitTransition: "border-radius 0.25s ease",
          transition: "border-radius 0.25s ease",
          WebkitTransitionDelay: "0.325s",
          transitionDelay: "0.325s",
          width: "100%",
        },
        ".ic-select>span:hover": { color: "#1dc4ba" },
        ".ic-select>span:after": {
          content: '"\\E809"',
          color: "theme.100",
          fontSize: "0.75em",
          fontFamily: "CamgoIcons",
          position: "absolute",
          top: "55%",
          right: "5%",
          WebkitTransform: "translateY(-50%)",
          transform: "translateY(-50%)",
        },
        ".ic-select>span em": { fontWeight: "bold", margin: "0 0.65em" },
        ".ic-select ul": {
          background: "#fff",
          borderRadius: "0 0 0.4em 0.4em",
          display: "none",
          margin: "0",
          padding: "0.5em 1em 0",
          position: "absolute",
          width: "100%",
        },
        ".ic-select ul li": { listStyleType: "none" },
        ".ic-select ul li input": { display: "none" },
        ".ic-select ul li label": {
          borderTop: "1px solid #dfe7ed",
          color: "background.100",
          cursor: "pointer",
          display: "block",
          marginBottom: "7px",
          fontSize: "0.9em",
          padding: "10px 5px",
          whiteSpace: "nowrap",
        },
        ".ic-select ul li label:hover": { color: "theme.100" },
        ".ic-select ul li label em": { margin: "0 0.25em" },
        ".ic-start": { marginTop: "1.5em" },
        ".ic-start strong": {
          color: "#fff",
          display: ["-webkit-box", "-ms-flexbox", "flex"],
          WebkitBoxPack: "center",
          msFlexPack: "center",
          justifyContent: "center",
          fontSize: "2em",
          letterSpacing: "0.045em",
          textTransform: "uppercase",
          whiteSpace: "nowrap",
        },
        ".ic-start strong em": {
          fontSize: "0.85em",
          msFlexItemAlign: "center",
          msGridRowAlign: "center",
          alignSelf: "center",
          verticalAlign: "sub",
        },
        ".ic-start strong em:after,.ic-start strong em:before": {
          display: "block",
          lineHeight: 0.25,
          position: "relative",
        },
        ".ic-start strong em:before": { opacity: 0.5, top: "0" },
        ".ic-start strong em:after": { content: '"\\E809"', top: "0.3em" },
        ".ic-start strong em:first-of-type": { marginRight: "1.5em" },
        ".ic-start strong em:last-child": { marginLeft: "1.5em" },
        ".ic-start strong.animate em:after,.ic-start strong.animate em:before": {
          WebkitAnimation: "arrow-down 1s linear infinite",
          animation: "arrow-down 1s linear infinite",
        },
        ".ic-start strong.animate em:after": {
          WebkitAnimationDelay: "0.2s",
          animationDelay: "0.2s",
        },
        ".ic-start .ics-btn": {
          display: ["-webkit-box", "-ms-flexbox", "flex"],
          WebkitBoxAlign: "center",
          msFlexAlign: "center",
          alignItems: "center",
          WebkitBoxPack: "center",
          msFlexPack: "center",
          justifyContent: "center",
          marginTop: "1.75em",
        },
        ".ic-start .ics-btn p": {
          color: "#fff",
          fontSize: "2em",
          fontWeight: 800,
          margin: "0 1em",
        },
        ".ic-start .ics-btn .btn": {
          borderRadius: "0.35em",
          color: "background.100",
          fontSize: "2.1em",
          fontWeight: 600,
          padding: "0.435em 20px",
          textAlign: "center",
          width: "50%",
        },
        ".ic-cont": {
          color: "#fff",
          display: ["-webkit-box", "-ms-flexbox", "flex"],
          WebkitBoxPack: "center",
          msFlexPack: "center",
          justifyContent: "center",
          marginTop: "2.35em",
          textAlign: "left",
          position: "relative",
        },
        ".ic-cont input": { position: "absolute", visibility: "hidden", zIndex: -1 },
        ".ic-cont input:checked+label:after": {
          WebkitTransform: "scale(1)",
          transform: "scale(1)",
        },
        ".ic-cont input:checked+label:before": { background: "theme.100" },
        ".ic-cont label": {
          cursor: "pointer",
          fontSize: "1.05em",
          fontWeight: 400,
          margin: "0",
          letterSpacing: "0.0175em",
          lineHeight: 1.45,
          paddingLeft: "2em",
          position: "relative",
          textAlign: "center",
          zIndex: 2,
        },
        ".ic-cont label a": {
          color: "#fff",
          WebkitTransition: "color .25s ease",
          transition: "color .25s ease",
        },
        ".ic-cont label a:hover": { color: "theme.100" },
        ".ic-cont label:before,.ic-cont label:after": {
          content: '""',
          position: "absolute",
        },
        ".ic-cont label:before": {
          background: "#fff",
          borderRadius: "0.3em",
          cursor: "pointer",
          left: "0",
          top: "0.085em",
          height: "1.26em",
          width: "1.26em",
        },
        ".ic-cont label:after": {
          content: '"\\E802"',
          fontSize: "1.15em",
          fontFamily: "CamgoIcons",
          fontWeight: "bold",
          lineHeight: 0,
          top: "0.5em",
          left: "0.1em",
          WebkitTransition: "-webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
          transition: [
            "-webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
            "transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
            "transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7), -webkit-transform 0.25s cubic-bezier(0.89, -0.74, 0.13, 1.7)",
          ],
          WebkitTransform: "scale(0)",
          transform: "scale(0)",
        },
        ".icc-error": {
          background: "#E94241",
          borderRadius: "3px",
          color: "#fff",
          fontSize: "14px",
          opacity: 0,
          padding: "4px 8px",
          position: "absolute",
          top: "-5px",
          left: "0px",
        },
        ".icc-error:after": {
          content: '""',
          border: "6px solid transparent",
          borderTop: "6px solid #E94241",
          position: "absolute",
          bottom: "-12px",
          left: "6px",
        },
        ".error .icc-error": {
          WebkitTransform: "translateY(-100%)",
          transform: "translateY(-100%)",
          opacity: 1,
        },
        ".ic-interests": { marginTop: "2em", position: "relative", zIndex: 2 },
        ".ic-interests .ici-area": {
          background: "#fff",
          borderRadius: "1em",
          cursor: "text",
          padding: "0.5em 1em",
          textAlign: "left",
          width: "100%",
        },
        ".ic-interests .ici-area form": {
          display: "inline-block",
          minWidth: "20em",
          verticalAlign: "middle",
        },
        ".ic-interests .ici-area form.no-holder": { minWidth: "10em" },
        ".ic-interests .ici-area input": {
          border: "0",
          fontSize: "1.525em",
          marginLeft: "auto",
          outline: "none",
          padding: "0.25em 0.25em 0.25em 0",
          width: "100%",
        },
        ".ic-interests .ici-area input::-ms-clear": { display: "none" },
        ".ic-interests .ici-area input::-moz-selection": { background: "theme.100" },
        ".ic-interests .ici-area input::selection": { background: "theme.100" },
        ".ic-interests .ici-area span": {
          background: "theme.100",
          borderRadius: "6px",
          color: "background.100",
          cursor: "pointer",
          display: "inline-block",
          WebkitBoxFlex: "1",
          msFlex: "1 0 auto",
          flex: "1 0 auto",
          fontSize: "1.2em",
          margin: "0.25em 0.5em 0.25em 0",
          padding: "2px 5px 2px 7px",
          verticalAlign: "middle",
          WebkitTransition: "all 0.25s ease",
          transition: "all 0.25s ease",
        },
        ".ic-interests .ici-area span:hover": { background: "#05c5b8" },
        ".ic-interests .ici-area span:hover em:before,.ic-interests .ici-area span:hover em::after": {
          height: "0.1em",
        },
        ".ic-interests .ici-area span em": {
          cursor: "pointer",
          display: "inline-block",
          marginLeft: "4px",
          position: "relative",
          top: "0",
          left: "0",
        },
        ".ic-interests .ici-area.show-list": {
          borderBottom: "1px solid #d9dbdc",
          borderRadius: "1em 1em 0 0",
        },
        ".ic-interests .ici-available": {
          background: "#fff",
          borderRadius: "0 0 1em 1em",
          display: "none",
          padding: "0.25em 0.5em 0.35em",
          position: "absolute",
          minHeight: "5.25em",
          height: "100%",
          width: "100%",
        },
        ".ic-interests .ici-available::-webkit-scrollbar": { width: "8px" },
        ".ic-interests .ici-available::-webkit-scrollbar-track": {
          background: "#d9dbdc",
          border: "4.5px solid transparent",
          backgroundClip: "content-box",
        },
        ".ic-interests .ici-available::-webkit-scrollbar-thumb": {
          background: "#9a9a9a",
          borderRadius: "10px",
        },
        ".ic-interests .ici-available .icia-list": {
          overflow: "auto",
          height: "100%",
        },
        ".ic-interests .ici-available .icia-list::-webkit-scrollbar": {
          width: "8px",
        },
        ".ic-interests .ici-available .icia-list::-webkit-scrollbar-track": {
          background: "#d9dbdc",
          border: "4.5px solid transparent",
          backgroundClip: "content-box",
        },
        ".ic-interests .ici-available .icia-list::-webkit-scrollbar-thumb": {
          background: "#9a9a9a",
          borderRadius: "10px",
        },
        ".ic-interests .ici-available span": {
          cursor: "pointer",
          display: "block",
          fontSize: "1.1em",
          textAlign: "left",
          padding: "0.15em 0.5em",
          WebkitTransition: "all 0.25s ease",
          transition: "all 0.25s ease",
        },
        ".ic-interests .ici-available span.active,.ic-interests .ici-available span:hover": {
          background: "#f4f4f4",
        },
        ".ic-interests .ici-available span.active::before,.ic-interests .ici-available span:hover::before": {
          color: "background.100",
        },
        ".ic-interests .ici-available span:before": {
          content: '"\\e807"',
          color: "#9a9a9a",
          marginRight: "0.35em",
          fontFamily: "CamgoIcons",
          display: "inline-block",
          verticalAlign: "middle",
        },
        ".learn-more": {
          cursor: "pointer",
          position: "absolute",
          bottom: "5px",
          right: "15px",
          maxWidth: "38em",
          width: "100%",
          textAlign: "center",
        },
        ".learn-more span": {
          color: "#fff",
          display: "inline-block",
          fontSize: "0.75em",
          letterSpacing: "0.1em",
        },
        ".learn-more span:before": {
          content: '"\\E809"',
          fontFamily: "CamgoIcons",
          display: "block",
          textAlign: "center",
          fontSize: "2.5em",
          lineHeight: 1,
        },
        "#app-loading": {
          display: "none",
          background: "background.100",
          position: "absolute",
          top: "0",
          left: "0",
          height: "100%",
          width: "100%",
          zIndex: 101,
        },
        "#app-loading .loader-body": {
          background: "url(/assets/img/logo-icon.svg) center/70% no-repeat",
          WebkitAnimation: "blink 1.25s infinite ease-in-out",
          animation: "blink 1.25s infinite ease-in-out",
          position: "absolute",
          top: "50%",
          left: "50%",
          WebkitTransform: "translate(-50%, -50%)",
          transform: "translate(-50%, -50%)",
          height: "200px",
          width: "200px",
        },
        ".feedback_link": { display: "none !important" },

        ".ft-img": { width: "60%", margin: "0 auto 2em" },
        ".ft-content": {
          WebkitBoxFlex: "1",
          msFlex: "auto",
          flex: "auto",
          fontSize: "0.85em",
          paddingLeft: "0",
          textAlign: "center",
        },
        ".ft-content p": { fontSize: "1.6em" },
        ".iwf-wrap": { msFlexWrap: "wrap", flexWrap: "wrap" },
        ".iwf-wrap>div": { width: "100%" },
        ".iwf-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, right top, color-stop(50%, rgba(255,255,255,0.53)), color-stop(0%, rgba(255,255,255,0))) bottom/30px 7px repeat-x",
            "linear-gradient(to right, rgba(255,255,255,0.53) 50%, rgba(255,255,255,0) 0%) bottom/30px 7px repeat-x",
          ],
          position: "absolute",
          top: "0",
          left: "0",
          width: "100%",
          height: "7px",
        },
        ".iwf-wrap>div+div img": { marginLeft: "0" },
        ".iwf-wrap>div+div .iwf-cont": { left: "45%" },
        ".iwf-wrap>div img": { marginLeft: "0", height: "80%", width: "70%" },
        ".iwf-wrap>div .iwf-cont": { left: "45%" },
        ".infographic-wrapper section.interest-based": { paddingBottom: "6em" },
        ".interest-based .container:after": {
          content: "''",
          background: "url(/assets/img/boy.svg) no-repeat",
          position: "absolute",
          bottom: "-2px",
          left: "3%",
          height: "8em",
          width: "6em",
        },
        ".interest-based h3": { fontSize: "2.25em" },
        ".ib-wrap": {
          msFlexWrap: "wrap",
          flexWrap: "wrap",
          margin: "0 auto",
          width: "75%",
        },
        ".ib-wrap>div": { margin: "0.5em auto", padding: "0.5em", width: "60%" },
        ".ib-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, right top, color-stop(50%, rgba(16,6,32,0.53)), color-stop(0%, rgba(255,255,255,0))) bottom/30px 7px repeat-x",
            "linear-gradient(to right, rgba(16,6,32,0.53) 50%, rgba(255,255,255,0) 0%) bottom/30px 7px repeat-x",
          ],
          position: "absolute",
          top: "0",
          left: "0",
          width: "100%",
          height: "7px",
        },
        ".infographic-wrapper section": { fontSize: "2.4vw", padding: "2em 0" },
        ".infographic-wrapper section:nth-of-type(even)": {
          backgroundSize: "30vw",
          padding: "3em 0",
        },
        ".vd-title": { fontSize: "0.85em", marginTop: "1.5em" },
        ".vd-wrap": { fontSize: "0.85em", marginTop: "3em" },
        ".vd-wrap:after": {
          content: "''",
          background: "url(../img/video-dating-usa.svg) center/contain no-repeat",
          WebkitTransform: "translate(-50%, -30%)",
          transform: "translate(-50%, -30%)",
          opacity: 0.15,
          position: "absolute",
          top: "50%",
          left: "50%",
          height: "90%",
          width: "90%",
          zIndex: 0,
        },
        ".vdw-score": {
          display: ["-webkit-box", "-ms-flexbox", "flex"],
          WebkitBoxAlign: "center",
          msFlexAlign: "center",
          alignItems: "center",
          WebkitBoxPack: "center",
          msFlexPack: "center",
          justifyContent: "center",
          WebkitBoxOrient: "vertical",
          WebkitBoxDirection: "normal",
          msFlexDirection: "column",
          flexDirection: "column",
          fontSize: "1.1em",
        },
        ".vdw-score strong": { fontSize: "5.5em", marginTop: "-0.5em" },
        ".vdw-list li:before": {
          content: "''",
          verticalAlign: "-0.6em",
          height: "2em",
          width: "2em",
        },
        ".vd-title h1": { fontSize: "2.25em" },
        "main section": { fontSize: "2.5vw", padding: "11em 0 8em" },
        ".head-mnu": { right: "-250px", width: "250px" },
        ".head-mnu li a": { fontSize: "18px", padding: "22px 0" },
        ".head-mnu li .get-plus": { fontSize: "18px", margin: "30px 0 0" },
        ".head-count": { lineHeight: 1.3 },
        ".inner-page .jumbotron h1": { fontSize: "36px" },
        ".inner-page .jumbotron p": { marginBottom: "0px", fontSize: "17px" },
        ".app-started #at-share-dock": { display: "none !important" },
        ".head-count em": {
          fontSize: "1.9em",
          marginRight: "5px",
          lineHeight: 0.5,
          verticalAlign: "bottom",
        },
        ".head-count span": {
          display: "inline-block",
          minWidth: "2.5em",
          lineHeight: 1,
          textAlign: "center",
        },
        ".head-count strong": {
          display: "block",
          fontSize: "0.65em",
          lineHeight: 0.7,
          textAlign: "right",
        },
        ".nav-open .app-intro,.nav-open main,.nav-open footer,.nav-open header": {
          right: "250px",
        },

        "main .container": {
          WebkitBoxOrient: "vertical",
          WebkitBoxDirection: "normal",
          msFlexDirection: "column",
          flexDirection: "column",
          WebkitBoxAlign: "center",
          msFlexAlign: "center",
          alignItems: "center",
          width: "95%",
        },
        "main .sn-img": {
          maxWidth: "12em",
          position: "absolute",
          top: "0%",
          WebkitTransform: "translateY(-30%)",
          transform: "translateY(-30%)",
          width: "100%",
          zIndex: 5,
        },
        "main .sn-content p": { lineHeight: 1.375 },
        "main.home-wrapper section:nth-of-type(1):before": {
          marginBottom: "4em",
          height: "4.4em",
        },
        "main.home-wrapper section:nth-of-type(1) .container": {
          paddingTop: "4.2em",
        },
        "main.home-wrapper section:nth-of-type(1) .sn-img": {
          WebkitTransform: "translateY(15%)",
          transform: "translateY(15%)",
        },
        "main.home-wrapper section:nth-of-type(3)": { marginTop: "-1.6em" },
        "main.home-wrapper section:nth-of-type(4) .container h3": {
          textAlign: "center",
        },
        "main.home-wrapper section:nth-of-type(5) .container h3": {
          marginBottom: "0.75em",
        },
        "main.home-wrapper section:nth-of-type(5) .sn-img": { maxWidth: "10em" },
        "main.modern-wrapper section": { padding: "9.5em 0 8.5em" },
        "main.modern-wrapper section:nth-of-type(1)": { marginTop: "10em" },
        "main.modern-wrapper section.sn-square": {
          marginTop: "0",
          paddingTop: "2em",
        },
        "main.modern-wrapper section.sn-square ul li": { width: "100%" },
        "main.modern-wrapper section.sn-square ul li+li": {
          paddingTop: "2em",
          marginTop: "2em",
        },
        "main.modern-wrapper section.sn-square ul li+li::after": {
          content: '""',
          background: [
            "-webkit-gradient(linear, right top, left top, color-stop(50%, #c7c7c7), color-stop(0%, rgba(255, 255, 255, 0))) top/18px 4px repeat-x",
            "linear-gradient(-90deg, #c7c7c7 50%, rgba(255, 255, 255, 0) 0%) top/18px 4px repeat-x",
          ],
          position: "absolute",
          top: "-2px",
          left: "0",
          height: "4px",
          width: "100%",
        },
        "main.modern-wrapper section.sn-square+section": { paddingBottom: "4em" },
        "main.modern-wrapper section.sn-list": { padding: "4em 0 8em" },
        "main.modern-wrapper section.sn-list li": { padding: "0", width: "100%" },
        "main.modern-wrapper .sn-img": {
          WebkitTransform: "translateY(-45%)",
          transform: "translateY(-45%)",
        },
        ".error-page .container": { fontSize: "2.25vw" },
      },
      "@media only screen and (max-width: 480px)": {
        ".app-intro": { fontSize: "2.1vw" },
        ".intro-content": { maxWidth: "90%" },
        ".ic-top": { marginBottom: "3em" },
        ".ic-top p": { fontSize: "2.25em", marginTop: "0.4em", lineHeight: 1.3 },
        ".ic-cont label": { fontSize: "1.6em" },
        ".ic-start .ics-btn,.ic-start": { marginTop: "2.5em" },
        ".ic-interests .ici-available span": { fontSize: "1.525em" },
        ".learn-more": { bottom: "15px" },
        ".learn-more span": { fontSize: "1.2em" },
        "#app-loading .loader-body": { height: "125px", width: "125px" },
        body: { paddingTop: "45px" },
        header: { height: "45px" },
        ".ft-img": { width: "72.5%", margin: "0 auto 3em" },
        ".ft-content": { fontSize: "0.95em" },
        ".ft-content p": { fontSize: "1.75em" },
        ".iwf-wrap>div+div:before": { backgroundSize: "20px 4px" },
        ".iwf-wrap>div img": { height: "85%", width: "72%" },
        ".iw-features p": {
          fontSize: "1.6em",
          maxWidth: "95%",
          margin: "0.2em 2.5% 1em",
        },
        ".interest-based h3": { fontSize: "2.3em", letterSpacing: "0" },
        ".interest-based p": {
          fontSize: "1.35em",
          maxWidth: "80%",
          margin: "2em 10% 0",
        },
        ".ib-wrap": { width: "85%" },
        ".ib-wrap>div": { margin: "0.75em auto", padding: "0.75em", width: "65%" },
        ".ib-wrap>div+div:before": { backgroundSize: "20px 4px" },
        ".infographic-wrapper .container": { width: "100%" },
        ".vd-wrap": { fontSize: "0.9em", margin: "5em 0 4em" },
        ".vd-title": { fontSize: "0.95em" },
        ".vd-title h1:before": { marginLeft: "0" },
        "header .container-fluid": { padding: "0 15px" },
        "main section": { fontSize: "3.2vw" },
        ".head-logo a": { width: "120px" },
        ".head-count": { fontSize: "13px" },
        ".head-toggle": { height: "22px", width: "28px" },
        ".head-toggle span": { height: "4px", width: "100%" },
        ".head-toggle span:nth-of-type(1)": { top: "0px" },
        ".head-toggle span:nth-of-type(2),.head-toggle span:nth-of-type(3)": {
          top: "9px",
        },
        ".head-toggle span:nth-of-type(4)": { top: "18px" },
        ".head-mnu": { padding: "45px 15px 15px" },
        ".head-mnu:before": { backgroundSize: "40%", height: "46px" },
        ".head-mnu li a": { fontSize: "17px", padding: "17px 0" },
        ".head-mnu li .get-plus": { fontSize: "16px", margin: "25px 0 0" },
        "footer .container": { padding: "30px 15px" },
        "footer nav li": { display: "block", marginBottom: "5px" },
        "footer nav li a": { fontSize: "16px" },
        ".fl-list nav": { width: "285px" },
        ".fl-list ul": { padding: "15px 25px" },
        ".fl-list ul li.fll-chse": { fontSize: "18px" },
        ".fl-list ul li a": { fontSize: "16px" },
        ".soc_wrap li a": {
          fontSize: "22px",
          lineHeight: "38px",
          height: "38px",
          width: "38px",
        },
        ".footer-langs span": { fontSize: "16px" },
        ".copy_wrap": { fontSize: "12px" },
        ".error-page .container": { fontSize: "2.75vw" },

        ".inner-page p": { fontSize: "15px" },
        ".inner-page .ipc-colored-title,.inner-page .jumbotron h1": {
          fontSize: "26px",
        },
        ".inner-page .ipc-sub-title": { fontSize: "21px" },
        ".inner-page .ipc-sub-small": { fontSize: "18px" },
        ".inner-page .tb-col p": { fontSize: "12px" },
        ".tb-col": { padding: "12px" },
      },
      ".trns, footer nav li a": {
        WebkitTransition: "all 0.25s ease",
        transition: "all 0.25s ease",
      },
      ".flex-center": {
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
      },
      ".flex-end": {
        WebkitBoxAlign: "end",
        msFlexAlign: "end",
        alignItems: "flex-end",
      },
      "main section:nth-of-type(even)": { background: "background.100" },
      "main section:nth-of-type(even) .sn-content P": { color: "#fff" },
      "main section:last-child": { paddingBottom: "4em" },
      "main section .sn-img img": { position: "relative", zIndex: 1 },
      "main .container": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxOrient: "horizontal",
        WebkitBoxDirection: "normal",
        msFlexDirection: "row",
        flexDirection: "row",
        position: "unset",
        width: "100%",
      },
      "main .sn-content": { width: "100%", paddingTop: "5%" },
      "main .sn-content h1, main .sn-content h2, main .sn-content h3": {
        color: "theme.100",
        fontSize: "1.9275em",
        fontWeight: 600,
        margin: "0 0 0.4em",
        lineHeight: 1.35,
      },
      "main .sn-content p": {
        color: "background.100",
        fontSize: "1.25em",
        letterSpacing: "0.45px",
        lineHeight: 1.55,
        margin: "0",
      },
      "main .sn-content p.m-none": { margin: "0" },
      "main .sn-content p a": { textDecoration: "none" },
      "main .sn-content p a:hover": { textDecoration: "underline" },
      "main .sn-content p+p": { marginTop: "45px" },
      "main.home-wrapper section:nth-of-type(1)": { paddingTop: "0" },
      "main.home-wrapper section:nth-of-type(1):before": {
        content: '""',
        background: "background.100",
        display: "block",
        marginBottom: "65px",
        height: "85px",
        width: "100%",
      },
      "main.modern-wrapper .sn-dots-list li": {
        listStyleType: "disc",
        marginLeft: "20px",
        paddingLeft: "5px",
      },
      "main.modern-wrapper .sn-square ul": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        msFlexWrap: "wrap",
        flexWrap: "wrap",
        overflow: "hidden",
      },
      "main.modern-wrapper .sn-square ul li": {
        position: "relative",
        width: "50%",
      },
      "main.modern-wrapper .sn-square ul li .sncs-img": {
        margin: "0 auto 1em",
        maxWidth: "15em",
        position: "relative",
        width: "100%",
      },
      "main.modern-wrapper .sn-square ul li .sncs-img:after": {
        content: '""',
        background: "url(img/dark-dots-bg.svg)",
        position: "absolute",
        top: "50%",
        left: "50%",
        WebkitTransform: "translate(-50%, -50%)",
        transform: "translate(-50%, -50%)",
        height: "110%",
        width: "110%",
      },
      "main.modern-wrapper .sn-square ul li .sncs-img img": {
        position: "relative",
        zIndex: 1,
      },
      "main.modern-wrapper .sn-square ul li strong": { display: "block" },
      "main.modern-wrapper .sn-list": { padding: "40px 0" },
      "main.modern-wrapper .sn-list h3": { marginBottom: "0.15em" },
      "main.modern-wrapper .sn-list ul": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        msFlexWrap: "wrap",
        flexWrap: "wrap",
      },
      "main.modern-wrapper .sn-list ul li": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        marginTop: "2em",
        paddingRight: "3em",
        width: "50%",
      },
      "main.modern-wrapper .sn-list ul li em": {
        background: "#42E9DF",
        borderRadius: "50%",
        color: "background.100",
        fontSize: "1.5em",
        lineHeight: "1.6em",
        marginRight: "0.725em",
        textAlign: "center",
        height: "1.6em",
        minWidth: "1.6em",
      },
      ".ip-notification": {
        background: "#efefef",
        borderRadius: "4px",
        borderLeft: "10px solid theme.100",
        marginBottom: "30px",
        padding: "20px 30px",
      },
      ".ip-notification p": { margin: "0" },
      ".error-page": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        WebkitBoxAlign: "center",
        msFlexAlign: "center",
        alignItems: "center",
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
      },
      ".error-page .container": {
        fontSize: "1.25vw",
        WebkitBoxOrient: "unset",
        WebkitBoxDirection: "unset",
        msFlexDirection: "unset",
        flexDirection: "unset",
        msFlexWrap: "wrap",
        flexWrap: "wrap",
        WebkitBoxPack: "center",
        msFlexPack: "center",
        justifyContent: "center",
        padding: "7.5em 0",
        textAlign: "center",
      },
      ".error-page .container h1": {
        fontSize: "6em",
        lineHeight: 1,
        margin: "0",
        width: "100%",
      },
      ".error-page .container P": { width: "100%" },
      ".error-page .container .btn": {
        borderRadius: "0.2em",
        WebkitBoxShadow: "0 -0.25em 0 rgba(0, 0, 0, 0.25) inset",
        boxShadow: "0 -0.25em 0 rgba(0, 0, 0, 0.25) inset",
        fontSize: "1.25em",
        fontWeight: 600,
        marginTop: "2em",
        padding: "0.75em 1.75em",
        textDecoration: "none",
        textTransform: "uppercase",
        textShadow: "2px 2px 2px rgba(0, 0, 0, 0.25)",
      },
      footer: { background: "#141a1f", color: "#fff", textAlign: "center" },
      "footer .container": { padding: "30px" },
      "footer nav li": { display: "inline-block", listStyleType: "none" },
      "footer nav li a": {
        color: "#eee",
        display: "block",
        fontSize: "18px",
        padding: "10px 20px",
        textDecoration: "none",
      },
      "footer nav li a:hover": { color: "theme.100" },
      "footer nav li:focus, footer nav li:hover": {
        background: "transparent",
        color: "#049f95",
      },
      ".footer-langs span": {
        color: "#fff",
        cursor: "pointer",
        display: "inline-block",
        fontSize: "18px",
        WebkitTransition: "all .25s ease",
        transition: "all .25s ease",
      },
      ".footer-langs span:hover": { color: "theme.100" },
      ".footer-langs span:before": {
        content: "''",
        background: "url(assets/img/lang-icon.svg) no-repeat",
        display: "inline-block",
        marginRight: "0.3em",
        verticalAlign: "-0.4em",
        height: "1.5em",
        width: "1.5em",
      },
      ".footer-langs span em": {
        fontSize: "0.65em",
        marginLeft: "0.5em",
        verticalAlign: ".05em",
      },
      ".fl-list": {
        display: "none",
        position: "fixed",
        top: "0",
        left: "0",
        height: "100%",
        width: "100%",
        zIndex: 1000001,
      },
      ".fl-list nav": {
        background: "#fff",
        border: "1px solid #d9dbdc",
        borderRadius: "3px",
        maxHeight: "0",
        overflow: "hidden",
        position: "absolute",
        top: "50%",
        left: "50%",
        WebkitTransition: ".35s max-height .15s linear",
        transition: ".35s max-height .15s linear",
        WebkitTransform: "translate(-50%, -50%)",
        transform: "translate(-50%, -50%)",
        width: "310px",
        zIndex: 1,
      },
      ".fl-list ul": { padding: "20px 30px" },
      ".fl-list ul li": { listStyleType: "none", textAlign: "left", width: "100%" },
      ".fl-list ul li+li:not(.fll-close)": { borderTop: "1px solid #c0cedb" },
      ".fl-list ul li.fll-close": {
        cursor: "pointer",
        position: "absolute",
        top: "11px",
        right: "7px",
        height: "14px",
        width: "14px",
      },
      ".fl-list ul li.fll-close:after, .fl-list ul li.fll-close:before": {
        content: "''",
        background: "background.100",
        marginTop: "-1px",
        position: "absolute",
        top: "50%",
        left: "0",
        height: "1px",
        width: "100%",
      },
      ".fl-list ul li.fll-close:before": {
        WebkitTransform: "rotateZ(45deg)",
        transform: "rotateZ(45deg)",
      },
      ".fl-list ul li.fll-close:after": {
        WebkitTransform: "rotateZ(-45deg)",
        transform: "rotateZ(-45deg)",
      },
      ".fl-list ul li.fll-close:hover::after, .fl-list ul li.fll-close:hover::before": {
        height: "1.5px",
      },
      ".fl-list ul li.fll-chse": {
        fontSize: "21px",
        color: "theme.100",
        paddingBottom: "10px",
        textShadow: "0 0",
      },
      ".fl-list ul li:last-child": { borderBottom: "0" },
      ".fl-list ul li a": {
        color: "background.100",
        display: "block",
        fontSize: "17px",
        letterSpacing: "0.25px",
        padding: "10px 0",
        textDecoration: "none",
      },
      ".fl-list ul li a:hover": { color: "theme.100", fontWeight: 600 },
      ".fl-list ul li .active": {
        color: "background.100",
        cursor: "default",
        fontWeight: 600,
      },
      ".fl-list ul li .active:hover": { color: "background.100" },
      ".fl-list ul li .active:after": {
        content: "'\\e802'",
        color: "theme.100",
        fontSize: "17px",
        fontFamily: "CamgoIcons",
        fontWeight: 400,
        cssFloat: "right",
      },
      ".fl-list.show nav": { maxHeight: "calc(100vh - 100px)", overflow: "auto" },
      ".fll-bg": {
        background: "rgba(27, 34, 41, 0.8)",
        position: "fixed",
        top: "0",
        left: "0",
        height: "100%",
        width: "100%",
      },
      ".soc_wrap": { margin: "20px auto 30px" },
      ".soc_wrap ul": { margin: "0", padding: "0" },
      ".soc_wrap li": {
        listStyleType: "none",
        display: "inline-block",
        verticalAlign: "top",
      },
      ".soc_wrap li a": {
        borderRadius: "50%",
        color: "#fff",
        display: "block",
        fontSize: "24px",
        lineHeight: "42px",
        margin: "0 10px",
        textAlign: "center",
        textDecoration: "none",
        WebkitTransition: "all 0.6s ease",
        transition: "all 0.6s ease",
        height: "42px",
        width: "42px",
      },
      ".soc_wrap li a.ci-facebook": { background: "#3b5998" },
      ".soc_wrap li a.ci-twitter": { background: "#4099ff" },
      ".soc_wrap li a.ci-youtube-play": { background: "#cc181e" },
      ".soc_wrap li a.ci-instagram": {
        background: [
          "#d6249f",
          "radial-gradient(circle at 30% 107%, #fdf497 0, #fdf497 5%, #fd5949 45%, #d6249f 60%, #285aeb 90%)",
        ],
      },
      ".soc_wrap li:hover a": {
        background: "#fff",
        WebkitTransform: "rotateY(360deg)",
        transform: "rotateY(360deg)",
      },
      ".soc_wrap li:hover a.ci-facebook": { color: "#3b5998" },
      ".soc_wrap li:hover a.ci-twitter": { color: "#4099ff" },
      ".soc_wrap li:hover a.ci-youtube-play": { color: "#cc181e" },
      ".soc_wrap li:hover a.ci-instagram": { color: "#d6249f" },
      ".copy_wrap": { marginTop: "25px" },
      ".copy_wrap p": { margin: "0" },

      "@media only screen and (max-device-width: 900px) and (min-aspect-ratio: 13 / 9)": {
        ".error-page .container": { fontSize: "1.5vw" },
      },
      "@media only screen and (max-width: 1300px)": {
        ".infographic-wrapper section": { fontSize: "17.5px" },
      },
      "@media only screen and (min-width: 1025px)": {
        ".home-welcone.container": { maxWidth: "1000px" },
        ".intro-content": { marginLeft: "auto" },
        ".intro-content:before": {
          content: '""',
          background: "url(/assets/img/intro-bg-dots.svg?v1) center/contain no-repeat",
          position: "absolute",
          left: "-25.75em",
          top: "50%",
          WebkitTransform: "translateY(-50%)",
          transform: "translateY(-50%)",
          height: "610px",
          width: "100%",
        },
        ".ic-cont": { fontSize: "13px" },
        ".ic-form": { position: "relative", zIndex: 2 },
        ".ft-img": { maxWidth: "45%" },
        ".iwf-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, rgba(255,255,255,0.53)), color-stop(0%, rgba(255,255,255,0))) right/4px 18px repeat-y",
            "linear-gradient(rgba(255,255,255,0.53) 50%, rgba(255,255,255,0) 0%) right/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "10%",
          left: "0",
          height: "70%",
          width: "4px",
        },
        ".ib-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, rgba(16,6,32,0.53)), color-stop(0%, rgba(16,6,32,0))) right/4px 18px repeat-y",
            "linear-gradient(rgba(16,6,32,0.53) 50%, rgba(16,6,32,0) 0%) right/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "10%",
          left: "0",
          height: "85%",
          width: "4px",
        },
        ".vdw-score": { paddingTop: "34%" },
        ".vdw-score:before": {
          content: "''",
          background: "url(assets/img/dots-bg-black.svg) no-repeat",
          position: "absolute",
          top: "-1%",
          left: "-3%",
          opacity: 0,
          WebkitTransform: "rotate(0) scale(0)",
          transform: "rotate(0) scale(0)",
          WebkitTransition: "1s all 0.5s cubic-bezier(0.49, 0.52, 0.25, 1.26)",
          transition: "1s all 0.5s cubic-bezier(0.49, 0.52, 0.25, 1.26)",
          height: "102%",
          width: "100%",
          zIndex: 0,
        },
        ".vdw-score.zoomIn:before": {
          WebkitTransform: "rotate(30deg) scale(1)",
          transform: "rotate(30deg) scale(1)",
          opacity: 0.6,
        },
        ".vdw-score:after": {
          content: "''",
          background: "url(assets/img/video-dating-usa.svg) center/cover no-repeat",
          position: "absolute",
          top: "0",
          left: "0",
          height: "100%",
          width: "98%",
          zIndex: 0,
        },
        ".vdw-list:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, rgba(151, 151, 151, 0.53)), color-stop(0%, rgba(151, 151, 151, 0))) right/4px 18px repeat-y",
            "linear-gradient(rgba(151, 151, 151, 0.53) 50%, rgba(151, 151, 151, 0) 0%) right/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "0",
          left: "0",
          height: "100%",
          width: "4px",
        },
        "main .sn-img": {
          minWidth: "245px",
          marginRight: "60px",
          position: "relative",
        },
        "main .sn-img.md-img": { minWidth: "265px" },
        "main .sn-img.lg-img": { minWidth: "315px", marginRight: "30px" },
        "main section:nth-of-type(even) .container": {
          WebkitBoxOrient: "horizontal",
          WebkitBoxDirection: "reverse",
          msFlexDirection: "row-reverse",
          flexDirection: "row-reverse",
        },
        "main section:nth-of-type(even) .sn-img": {
          marginLeft: "60px",
          marginRight: "0",
        },
        "main section:nth-of-type(even) .sn-img.lg-img": {
          marginRight: "0",
          marginLeft: "60px",
        },
        "main.home-wrapper section:nth-of-type(1)": { paddingBottom: "120px" },
        "main.home-wrapper section:nth-of-type(1) .sn-img": {
          minWidth: "300px",
          marginRight: "45px",
        },
        "main.home-wrapper section:nth-of-type(2)": { paddingBottom: "125px" },
        "main.home-wrapper section:nth-of-type(2) .sn-img": { marginTop: "55px" },
        "main.home-wrapper section:nth-of-type(3) .sn-img": { marginTop: "10px" },
        "main.home-wrapper section:nth-of-type(4)": { padding: "120px 0 135px" },
        "main.home-wrapper section:nth-of-type(4) .sn-img": { minWidth: "260px" },
        "main.home-wrapper section:nth-of-type(5)": { paddingTop: "95px" },
        "main.home-wrapper section:nth-of-type(5) .sn-img": { marginRight: "75px" },
        "main.home-wrapper section:nth-of-type(6)": { paddingTop: "120px" },
        "main.home-wrapper section:nth-of-type(6) .sn-img": { marginTop: "20px" },
        "main.modern-wrapper section": { padding: "55px 0 90px" },
        "main.modern-wrapper section:nth-of-type(1) .sn-img": { marginTop: "75px" },
        "main.modern-wrapper section:nth-of-type(even)": { overflow: "hidden" },
        "main.modern-wrapper section:nth-of-type(even) .sn-img:before": {
          content: '""',
          background: "url(assets/img/dots-bg.svg) no-repeat",
          position: "absolute",
          top: "50%",
          left: "50%",
          WebkitTransform: "translate(-50%, -50%)",
          transform: "translate(-50%, -50%)",
          height: "600px",
          width: "600px",
        },
        "main.modern-wrapper section.sn-square ul li .sncs-img": {
          margin: "0 auto -10px",
          maxWidth: "350px",
        },
        "main.modern-wrapper section.sn-square ul li .sncs-img:after": {
          content: '""',
          background: "url(assets/img/dark-dots-bg.svg)",
          position: "absolute",
          top: "50%",
          left: "50%",
          WebkitTransform: "translate(-50%, -50%)",
          transform: "translate(-50%, -50%)",
          height: "110%",
          width: "110%",
        },
        "main.modern-wrapper section.sn-square ul li .sncs-img img": {
          position: "relative",
          zIndex: 1,
        },
        "main.modern-wrapper section.sn-square ul li:nth-of-type(even)": {
          paddingLeft: "1.85em",
        },
        "main.modern-wrapper section.sn-square ul li:nth-of-type(even)::before": {
          content: '""',
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, #c7c7c7), color-stop(0%, rgba(255, 255, 255, 0))) left/4px 18px repeat-y",
            "linear-gradient(#c7c7c7 50%, rgba(255, 255, 255, 0) 0%) left/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "0",
          left: "-2px",
          height: "100%",
          width: "4px",
        },
        "main.modern-wrapper section.sn-square ul li:nth-of-type(odd)": {
          paddingRight: "1.85em",
        },
        "main.modern-wrapper section.sn-square ul li:nth-of-type(1),main.modern-wrapper section.sn-square ul li:nth-of-type(2)":
          {
            paddingBottom: "4.25em",
          },
        "main.modern-wrapper section.sn-square ul li:nth-of-type(3)::after,main.modern-wrapper section.sn-square ul li:nth-of-type(4)::after":
          {
            content: '""',
            background: [
              "-webkit-gradient(linear, right top, left top, color-stop(50%, #c7c7c7), color-stop(0%, rgba(255, 255, 255, 0))) top/18px 4px repeat-x",
              "linear-gradient(-90deg, #c7c7c7 50%, rgba(255, 255, 255, 0) 0%) top/18px 4px repeat-x",
            ],
            position: "absolute",
            top: "-2px",
            left: "0",
            height: "4px",
            width: "100%",
          },
      },
      "main, footer, .inner-body main, .home-welcone": {
        opacity: 1,
        WebkitTransition: "right 0.5s ease, opacity 0.5s ease",
        transition: "right 0.5s ease, opacity 0.5s ease",
      },
      ".inner-page": {
        borderRadius: "5px",
        color: "background.100",
        margin: "30px auto 100px",
      },
      ".inner-page .jumbotron": {
        borderBottom: "2px solid #07d1c5",
        margin: "0 0 20px",
        padding: "20px 0",
      },
      ".inner-page .jumbotron h1": {
        color: "theme.100",
        fontSize: "50px",
        margin: "0 0 3px",
      },
      ".inner-page .jumbotron p": { fontSize: "17px", margin: "0" },
      ".inner-page .ipc-sub-title": {
        fontSize: "26px",
        fontWeight: 600,
        margin: "60px 0 10px",
        textTransform: "uppercase",
      },
      ".inner-page .ipc-sub-small": {
        fontSize: "22px",
        fontWeight: 600,
        margin: "35px 0 10px",
      },
      ".inner-page .ipc-colored-title": {
        borderTop: "1px solid #bfbfbf",
        color: "theme.100",
        fontSize: "40px",
        textTransform: "capitalize",
        paddingTop: "40px",
      },
      ".inner-page p": { fontSize: "16px", margin: "5px 0 10px" },
      ".inner-page a": {
        color: "theme.100",
        WebkitTransition: "all 0.25s ease",
        transition: "all 0.25s ease",
      },
      ".inner-page a:hover": { color: "#04b8ad", textDecoration: "none" },
      ".inner-page .ipc-nav": { listStyleType: "decimal" },
      ".inner-page .ipc-nav li": { marginBottom: "10px" },
      ".inner-page .ipc-nav li:before": { marginTop: "-4.5px", top: "50%" },
      ".inner-page .ipc-nav.ipc-top-nav": { marginTop: "50px" },
      ".inner-page .ipc-nav.ipc-top-nav li": { fontSize: "18px" },
      ".inner-page ul": { paddingLeft: "20px" },
      ".inner-page ul li": {
        fontSize: "16px",
        padding: "0 5px",
        position: "relative",
      },
      ".inner-page ul li:before": {
        content: '""',
        border: "2px solid theme.100",
        borderRadius: "50%",
        position: "absolute",
        left: "-12px",
        top: "6px",
        height: "5px",
        width: "5px",
      },
      ".inner-page ul li a": { display: "inline-block" },
      ".table-wrap": {
        border: "1px solid #c5c5c5",
        borderStyle: "solid solid none none",
        margin: "50px 0",
        overflow: "auto",
      },
      ".table-head": { background: "#dbf1f0", fontWeight: 600 },
      ".table-wrap>div, .tb-row": {
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        msFlexWrap: "wrap",
        flexWrap: "wrap",
        WebkitBoxOrient: "vertical",
        WebkitBoxDirection: "normal",
        msFlexDirection: "column",
        flexDirection: "column",
        minWidth: "750px",
      },
      ".tb-row": {
        WebkitBoxOrient: "horizontal",
        WebkitBoxDirection: "normal",
        msFlexDirection: "row",
        flexDirection: "row",
        width: "100%",
      },
      ".tb-col": {
        borderLeft: "1px solid #c5c5c5",
        borderBottom: "1px solid #c5c5c5",
        display: ["-webkit-box", "-ms-flexbox", "flex"],
        msFlexWrap: "wrap",
        flexWrap: "wrap",
        WebkitBoxOrient: "vertical",
        WebkitBoxDirection: "normal",
        msFlexDirection: "column",
        flexDirection: "column",
        padding: "20px",
      },
      ".tb-col p": { marginBottom: "10px" },
      ".privacy-table .tb-col": { width: "33.33%" },
      ".cookie-table .tb-col": { width: "20%" },

      "@media only screen and (max-width: 768px)": {
        ".inner-page": { width: "95%" },
        ".tb-col": { padding: "15px" },
        ".inner-page .ipc-sub-title": { fontSize: "23px", margin: "50px 0 10px" },
        ".inner-page .ipc-colored-title": { fontSize: "32px" },
        ".inner-page .ipc-sub-small": { fontSize: "20px" },
      },
      "@media only screen and (max-width: 600px)": {
        ".inner-page .jumbotron h1": { fontSize: "29px" },
        ".inner-page .jumbotron p": { fontSize: "15px" },
      },
      ".atss .at-share-btn span .at-icon, .atss a span .at-icon": {
        width: "26px !important",
        height: "26px !important",
        lineHeight: "26px !important",
      },
      ".at-custom-sidebar-counter": { background: "#fff" },
      "@media only screen and (max-width: 1200px)": {
        ".at-share-btn .at-label": { display: "none" },
        ".infographic-wrapper section": { fontSize: "15px" },
      },
      "@media only screen and (max-width: 979px)": {
        ".at-share-dock.atss": {
          WebkitBoxShadow: "none !important",
          boxShadow: "none !important",
        },
        ".at-share-dock.at-shfs-medium .at-share-btn .at-icon-wrapper,.at-share-dock.at-shfs-medium a .at-icon-wrapper":
          {
            padding: "2px 0 !important",
          },
        ".at-share-dock.at-shfs-medium .at4-count": {
          height: "30px !important",
          paddingTop: "0 !important",
        },
        ".at-share-dock.at-shfs-medium .at4-count .at4-counter": {
          fontSize: "14px !important",
          lineHeight: "14px !important",
          top: "3px !important",
        },
        ".at-share-dock .at4-count .at4-share-label": { fontSize: "8px !important" },
      },
      "@media only screen and (min-width: 980px)": {
        ".atss .at-share-btn,.atss a": {
          width: "38px !important",
          height: "38px !important",
        },
        ".atss .at-share-btn:focus,.atss .at-share-btn:hover,.atss a:focus,.atss a:hover": {
          width: "46px !important",
        },
        ".at4-share .at-custom-sidebar-counter": {
          cssFloat: "right",
          marginRight: "0 !important",
          width: "38px !important",
        },
        ".at4-share .at-custom-sidebar-text": { fontSize: "7px !important" },
        ".at4-share .at-custom-sidebar-count": {
          fontSize: "14px !important",
          padding: "1px 0",
        },
      },
      "@media only screen and (max-width: 400px)": {
        ".head-count": { fontSize: "12px" },
      },
      "@media only screen and (max-width: 600px) and (max-aspect-ratio: 4 / 3)": {
        ".app-intro": { fontSize: "1.7vw" },
        ".intro-content": { maxWidth: "80%" },
      },
      "@media only screen and (max-device-width: 1024px) and (min-aspect-ratio: 4 / 3)": {
        ".app-intro": { fontSize: "1vw" },
        ".home-welcone": { width: "90%" },
        ".intro-content": { marginRight: "0", maxWidth: "50%", padding: "0" },
        ".intro-content:before": {
          content: '""',
          background: "url(/assets/img/intro-bg-dots.svg?v1) left/contain no-repeat",
          display: "block",
          position: "absolute",
          left: "-10%",
          top: "50%",
          WebkitTransform: "translateY(-50%)",
          transform: "translateY(-50%)",
          height: "80vh",
          width: "100%",
        },
        ".ic-top": { marginBottom: "2em" },
        ".ic-top p": { display: "none" },
        ".ic-start": { marginTop: "2.25em" },
        ".ic-start strong": { display: "none" },
        ".ic-start .ics-btn": { marginTop: "2.25em" },
        ".ic-cont label": { fontSize: "1.35em" },
        ".learn-more": {
          bottom: "10px",
          maxWidth: "50%",
          right: "7.5px",
          WebkitTransform: "translateX(0%)",
          transform: "translateX(0%)",
          width: "100%",
        },
        ".ft-img": { width: "40%" },
        ".iwf-wrap>div": { width: "50%" },
        ".iwf-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, rgba(255,255,255,0.53)), color-stop(0%, rgba(255,255,255,0))) right/4px 18px repeat-y",
            "linear-gradient(rgba(255,255,255,0.53) 50%, rgba(255,255,255,0) 0%) right/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "10%",
          left: "0",
          height: "70%",
          width: "4px",
        },
        ".iwf-wrap>div .iwf-cont h4": { fontSize: "1.5em" },
        ".iw-features p": { fontSize: "1.1em" },
        ".ib-wrap": { marginTop: "1em", width: "100%" },
        ".ib-wrap>div": { width: "33.3%" },
        ".ib-wrap>div img": { width: "85%", margin: "0 auto 0.5em" },
        ".ib-wrap>div+div:before": {
          content: "''",
          background: [
            "-webkit-gradient(linear, left top, left bottom, color-stop(50%, rgba(16,6,32,0.53)), color-stop(0%, rgba(16,6,32,0))) right/4px 18px repeat-y",
            "linear-gradient(rgba(16,6,32,0.53) 50%, rgba(16,6,32,0) 0%) right/4px 18px repeat-y",
          ],
          position: "absolute",
          top: "10%",
          left: "0",
          height: "85%",
          width: "4px",
        },
        "main section": { fontSize: "2.2vw" },
        ".infographic-wrapper section": { fontSize: "1.75vw" },
        ".vd-wrap": { width: "80%" },
        ".vd-wrap:after": { height: "100%" },
      },
      "@media only screen and (max-width: 900px) and (min-aspect-ratio: 13 / 9)": {
        ".app-intro": { fontSize: "2vh" },
        ".home-welcone": { maxWidth: "650px" },
        ".intro-content": { maxWidth: "55%", padding: "0 0 50px" },
        ".intro-content:before": { height: "90vh" },
        ".ic-start": { marginTop: "2em" },
        ".ic-start .ics-btn": { marginTop: "0" },
        ".ic-start strong": { display: "none" },
        ".ic-interests,.ic-cont": { marginTop: "2em" },
        ".learn-more": { maxWidth: "55%", right: "7px" },
        "body:not(.inner-body)": { paddingTop: "0" },
        "body:not(.inner-body) header": { height: "45px", top: "-45px" },
        "body:not(.inner-body) header.fixed-nav": { top: "0" },
        body: { paddingTop: "43px" },
        "main section": { fontSize: "1.8vw" },
        ".head-logo a": { margin: "4px 0 0", width: "110px" },
        ".head-logo a img": { minHeight: "0" },
        ".head-count": { fontSize: "13px" },
        ".head-mnu li a": { fontSize: "16px", padding: "15px 0" },
        ".head-mnu li .get-plus": { fontSize: "15px", margin: "15px 0 0" },
        ".head-toggle": { height: "22px", width: "28px" },
        ".head-toggle span": { height: "4px", width: "100%" },
        ".head-toggle span:nth-of-type(1)": { top: "0px" },
        ".head-toggle span:nth-of-type(2),.head-toggle span:nth-of-type(3)": {
          top: "9px",
        },
        ".head-toggle span:nth-of-type(4)": { top: "18px" },
      },
      "@media only screen and (min-width: 481px)": {
        ".head-logo img": { minHeight: "47px" },
      },
    }),
  },
  components: {
    Text,
    Link,
    Heading,
  },
});

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <ChakraProvider theme={theme}>
      <Fonts />
      <Component {...pageProps} />
    </ChakraProvider>
  );
}
export default MyApp;
