import Head from "next/head";

import { Box, Flex, Image, Text, Button } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="modern-wrapper">
        <section>
          <div className="container">
            <div className="sn-img lg-img">
              <img className="img-responsive" src="../assets/img/intellegent-cam.svg" alt="" />
            </div>
            <div className="sn-content">
              <h1>Camgo – The Intelligent Live Cam Social Network</h1>
              <p>
                Welcome to the world’s first intelligent live cam social network - Camgo. Your first question is
                probably, “What exactly is intelligent video chat?” Imagine a video chat platform that filters
                connections according to your preferences. At Camgo, we have developed a highly sophisticated AI system
                called Safe Search. This system automatically connects you to live cam streams that are considered
                “safe”, reducing your risk of viewing adult content.
              </p>
              <p>
                The <strong>Safe Search</strong> system offers you multiple benefits, including:
              </p>
              <ul className="sn-dots-list">
                <li>
                  <p>Search is automatically activated when you hit the start button and enter the video chat app.</p>
                </li>
                <li>
                  <p>You will only connect with random cam users that the AI considers safe.</p>
                </li>
                <li>
                  <p>You can chat with confidence, knowing that you are much less likely to see unwanted content.</p>
                </li>
                <li>
                  <p>You can turn Safe Search off if you wish to use the unfiltered random cam chat.</p>
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img lg-img">
              <img className="img-responsive" src="../assets/img/launch.svg" alt="" />
            </div>
            <div className="sn-content">
              <h2>Why We Launched Camgo</h2>
              <p>
                A combination of personal experience and feedback from people who love random chat like you discovered
                two common issues with the video chat world. The first is an inability to connect directly with people
                who share your interests. The second is far too many adult-related streams due to the random nature of
                the chat. Camgo addresses both issues, allowing you to meet new friends who share your interests in a
                safer environment while maintaining the most important elements – randomness and fun!
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="../assets/img/enhances-online.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>How Camgo Enhances Online Stranger Chat</h3>
              <p>
                Our primary goal is to develop a video chat app that is not just a gateway for explicit and
                inappropriate material. Too many live cam sites are minefields, making it tiresome and boring when
                trying to meet friends and enjoy socially distanced live chat. Therefore, months were spent developing
                and refining both an AI system to scan for inappropriate web cameras and a simple chat platform for you.
                The result is Camgo, a perfect chat app to talk, flirt, and date online.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img md-img">
              <img className="img-responsive" src="../assets/img/safe-search.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>What is Safe Search?</h3>
              <p>
                At Camgo, we have developed an advanced AI system that can detect when users are misbehaving or showing
                inappropriate material on their live web camera. To keep random video chat fun for everyone, you can
                choose to enable or disable “Safe Search.” When enabled, our AI system scans potential matches and only
                connects you with those who are considered safe.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="../assets/img/strangers.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>Thousands of People Already Use Camgo</h3>
              <p>
                Since launching, Camgo has grown faster than anyone could have anticipated. The video chat app has
                exploded from just a handful of loyal users to thousands of random strangers chatting simultaneously
                every single day. Finding friends is incredibly easy with such a large pool of users to choose from on
                Camgo!
              </p>
            </div>
          </div>
        </section>
      </main>{" "}
      <Footer />
    </div>
  );
}
