import Head from "next/head";

import { Box, Flex, Image, Text, Button } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="infographic-wrapper">
        <section className="video-dating">
          <Box className="container">
            <Box className="vd-title text-center">
              <h1>Socially Distanced</h1>
              <strong>Video Dating</strong>
            </Box>
            <Box className="vd-wrap">
              <Box className="vdw-score animated zoomIn" style={{ opacity: 1 }}>
                <strong>+35%</strong>
                <Text>increase in users across the United States</Text>
              </Box>
              <Box className="vdw-list">
                <ul>
                  <li style={{ opacity: 1 }}>
                    California <span>+40%</span>
                  </li>
                  <li style={{ opacity: 1 }}>
                    New York <span>+33%</span>
                  </li>
                  <li style={{ opacity: 1 }}>
                    Arizona <span>+29%</span>
                  </li>
                  <li style={{ opacity: 1 }}>
                    Georgia <span>+29%</span>
                  </li>
                  <li style={{ opacity: 1 }}>
                    Pennsylvania <span>+27%</span>
                  </li>
                </ul>
              </Box>
            </Box>
          </Box>
        </section>
        <section className="five-times">
          <Box className="container">
            <Box className="bounceInLeft ft-img">
              <Image className="img-responsive" src="../assets/img/7-times-more.svg" alt="" />
            </Box>
            <Box className="ft-content anim-right">
              <h2>
                <span>7 times more</span> users online at any given time
              </h2>
              <Text>
                The average number of people using camgo video chat at any given time has increased seven-fold over the
                past six months.
              </Text>
            </Box>
          </Box>
        </section>
        <section className="iw-features">
          <Box className="container">
            <Box className="iwf-wrap">
              <Box className="iwf-item">
                <Box className="anim-left">
                  <Image src="../assets/img/time-spent.svg" alt="" />
                  <Box className="iwf-cont">
                    <h4>
                      Time Spent Per Chat Up by <span>40%</span>
                    </h4>
                  </Box>
                </Box>
              </Box>
              <Box className="iwf-item">
                <Box className="anim-right">
                  <Image src="../assets/img/number-messages.svg" alt="" />
                  <Box className="iwf-cont">
                    <h4>
                      <span>35%</span> More Messages Shared
                    </h4>
                  </Box>
                </Box>
              </Box>
            </Box>
            <Text className="text-center anim-up">
              The average time spent per chat (up 40%) and the number of messages shared in every chat (up 35%) has
              increased over the past six months to establish more meaningful chats across Camgo.
            </Text>
          </Box>
        </section>
        <section className="interest-based">
          <Box className="container text-center">
            <h3 className="anim-left">
              Top <span>Interest-Based</span> Searches
            </h3>
            <Box className="ib-wrap">
              <Box className="ib-item">
                <Image className="img-responsive" src="../assets/img/covid-dating.svg" alt="" />
                <h4>Covid Dating</h4>
              </Box>
              <Box className="ib-item">
                <Image className="img-responsive" src="../assets/img/virtual-date.svg" alt="" />
                <h4>Virtual Date</h4>
              </Box>
              <Box className="ib-item">
                <Image className="img-responsive" src="../assets/img/dating.svg" alt="" />
                <h4>Dating</h4>
              </Box>
            </Box>
            <Text>
              *Data presented from camgo analytics between May 2020 and October 2020 compared to data between November
              2019 to April 2020. Compiled and copyright www.camgo.com.
            </Text>
          </Box>
        </section>
      </main>
      <Footer />
    </Box>
  );
}
