import Head from "next/head";

import { Box, Flex, Image, Text, Button } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="app-intro">
        <div className="home-welcone container">
          <div className="intro-content">
            <div className="ic-top">
              <strong>Welcome to Camgo!</strong>
              <p>
                Socially Distanced <span className="green-text">Video Chat</span> for Meeting New People.
              </p>
            </div>
            <div className="ic-form">
              <div id="rlt-gender-select" className="ic-select">
                <span className="trns">Select Your Gender</span>
                <ul>
                  <li>
                    <input type="radio" id="m-gndr" name="gender" value="m" />
                    <label htmlFor="m-gndr">
                      {" "}
                      <span>I am</span> <em className="ci ci-mars"></em> Male{" "}
                    </label>
                  </li>
                  <li>
                    <input type="radio" id="f-gndr" name="gender" value="f" />
                    <label htmlFor="f-gndr">
                      {" "}
                      <span>I am</span> <em className="ci ci-venus"></em> Female{" "}
                    </label>
                  </li>
                  <li>
                    <input type="radio" id="t-gndr" name="gender" value="t" />
                    <label htmlFor="t-gndr">
                      {" "}
                      <span>I am</span> <em className="ci ci-transgender-icon"></em> Transgender{" "}
                    </label>
                  </li>
                  <li>
                    <input type="radio" id="c-gndr" name="gender" value="c" />
                    <label htmlFor="c-gndr">
                      {" "}
                      <span>We are</span> <em className="ci ci-unisex"></em> Couple{" "}
                    </label>
                  </li>
                </ul>
              </div>
              <div className="ic-start login_button">
                <strong>
                  <em className="ci ci-arrow-light"></em> Start Chat <em className="ci ci-arrow-light"></em>
                </strong>
                <div className="ics-btn">
                  <span id="rlt-start-text" className="btn green-btn trns">
                    Text
                  </span>
                  <p>or</p>
                  <span id="rlt-start-video" className="btn green-btn trns">
                    Video
                  </span>
                  <div id="rlt-start-btn"></div>
                </div>
              </div>
              <div className="ic-cont gf-terms">
                <input type="checkbox" id="hcw-check" className="rlt-terms-cb" />
                <label htmlFor="hcw-check">
                  I certify I have read and agree to the
                  <a href="legal/terms/index.htm" target="_blank">
                    Terms-of-Use Agreement
                  </a>
                  . I certify I am at least 18-years old and have reached the age of majority where I live.
                </label>
                <span className="icc-error trns">You must agree to continue</span>
              </div>
              <div className="ic-interests">
                <div className="ici-area">
                  <form className="rlt-interests-form" action="#">
                    <input
                      type="text"
                      aria-label="interests"
                      placeholder="Add your interests (optional)"
                      size={1}
                      maxLength={15}
                    />
                    <input type="submit" hidden={false} />
                  </form>
                </div>
                <div className="ici-available">
                  <div className="icia-list"></div>
                </div>
              </div>
            </div>
          </div>
          <div className="learn-more">
            <span>learn more</span>
          </div>
        </div>
        <div id="app-loading">
          <div className="loader-body"></div>
        </div>
        <div id="app" className="home-player"></div>
      </div>
      <main className="home-wrapper">
        <section>
          <div className="container">
            <div className="sn-img lg-img">
              <img className="img-responsive" src="assets/img/date-online.svg" alt="" />
            </div>
            <div className="sn-content">
              <h1>Camgo – Chat, Talk, Flirt & Date Online</h1>
              <p>
                Camgo is an easy way to meet friends online – perfect for maintaining your social life while practicing
                social distancing. Using the latest random video chat technology, Camgo provides an anonymous and safe
                way to chat with strangers. The system chooses a random stranger from a pool of thousands of people and
                creates a chat room where you can make new friends one-on-one. It’s simple, fun, and safe!
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img lg-img">
              <img className="img-responsive" src="assets/img/video-chat.svg" alt="" />
            </div>
            <div className="sn-content">
              <h2>Text Chat, Video Chat, or Both?</h2>
              <p>There are three main ways to talk to strangers on Camgo – text chat, video chat, or both.</p>
              <p>
                <strong>Text chat</strong>– Perfect for beginners and people who are shy at first. Text chat is like the
                “lite mode” of Camgo, where you can still meet people but cannot see them, and they cannot see you.
              </p>
              <p>
                <strong>Video chat</strong> – A great way to truly engage with the random chat platform and match with
                thousands of other people streaming on webcam.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="assets/img/strangers.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>Match with Like-Minded Strangers</h3>
              <p>
                If you want to find like-minded people, use the “What do you want to chat about?’ box. Just add
                interests and hobbies to match with people who enjoy the same things as you. Adding interests can be a
                great way to narrow your matches when finding friends instead of connecting with totally random
                strangers.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="assets/img/safe-search.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>What is Safe Search?</h3>
              <p>
                At Camgo, we have developed an advanced AI system that can detect when users are misbehaving or showing
                inappropriate material on their live web camera. To keep random video chat fun for everyone, you can
                choose to enable or disable “Safe Search.” When enabled, our AI system scans potential matches and only
                connects you with those who are considered safe.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="assets/img/5-tips.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>5 Tips for Staying Safe on Cam Chat</h3>
              <p>
                Add interests to meet more like-minded people to increase your chances of meeting new friends and reduce
                the randomness of chat connections.
              </p>
              <p>Leave “Safe Search” turned on and match with filtered random video users.</p>
              <p>
                Camgo anonymous chat does not request personal information. We recommend that you do not reveal any
                identifiable details about yourself in the chat room.
              </p>
              <p>Keep your face visible at all times while using the random chat.</p>
              <p>
                If a stranger chat becomes too intense, use the “next” button to leave the cam chat and match with new
                friends quickly.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="sn-img">
              <img className="img-responsive" src="assets/img/new-friends.svg" alt="" />
            </div>
            <div className="sn-content">
              <h3>New Friends Are Waiting Right Now</h3>
              <p>
                Click the start button and instantly enter the free chat app where thousands of potential new friends
                are waiting at this very moment. However, be warned that once you give Camgo a try, hours will feel like
                minutes and other social network platforms may start to feel boring compared to the fast-paced cam chat
                on Camgo!
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
