import Head from "next/head";
import React from "react";
import { Box, Flex, Image, Text, Button, Input } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { css } from "@emotion/css";
import WelcomeScreen from "../components/welcomeScreen";
import ChatBox from "../components/chat";
export default function Home() {
  const [screen, setScreen] = React.useState(true);
  return (
    <Box>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div style={{ marginTop: 55 }}>
        <ChatBox />
      </div>
      <Box className="app-intro">
        {screen == true ? <></> : <WelcomeScreen />}

        <Box id="app-loading">
          <Box className="loader-body"></Box>
        </Box>
        <Box id="app" className="home-player"></Box>
      </Box>
      <main className="home-wrapper">
        <section>
          <Box className="container">
            <Box className="sn-img lg-img">
              <Image className="img-responsive" src="assets/img/date-online.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h1>Camgo – Chat, Talk, Flirt & Date Online</h1>
              <Text>
                Camgo is an easy way to meet friends online – perfect for maintaining your social life while practicing
                social distancing. Using the latest random video chat technology, Camgo provides an anonymous and safe
                way to chat with strangers. The system chooses a random stranger from a pool of thousands of people and
                creates a chat room where you can make new friends one-on-one. It’s simple, fun, and safe!
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container">
            <Box className="sn-img lg-img">
              <Image className="img-responsive" src="assets/img/video-chat.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h2>Text Chat, Video Chat, or Both?</h2>
              <Text>There are three main ways to talk to strangers on Camgo – text chat, video chat, or both.</Text>
              <Text>
                <strong>Text chat</strong>– Perfect for beginners and people who are shy at first. Text chat is like the
                “lite mode” of Camgo, where you can still meet people but cannot see them, and they cannot see you.
              </Text>
              <Text>
                <strong>Video chat</strong> – A great way to truly engage with the random chat platform and match with
                thousands of other people streaming on webcam.
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container">
            <Box className="sn-img">
              <Image className="img-responsive" src="assets/img/strangers.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h3>Match with Like-Minded Strangers</h3>
              <Text>
                If you want to find like-minded people, use the “What do you want to chat about?’ box. Just add
                interests and hobbies to match with people who enjoy the same things as you. Adding interests can be a
                great way to narrow your matches when finding friends instead of connecting with totally random
                strangers.
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container">
            <Box className="sn-img">
              <Image className="img-responsive" src="assets/img/safe-search.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h3>What is Safe Search?</h3>
              <Text>
                At Camgo, we have developed an advanced AI system that can detect when users are misbehaving or showing
                inappropriate material on their live web camera. To keep random video chat fun for everyone, you can
                choose to enable or disable “Safe Search.” When enabled, our AI system scans potential matches and only
                connects you with those who are considered safe.
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container">
            <Box className="sn-img">
              <Image className="img-responsive" src="assets/img/5-tips.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h3>5 Tips for Staying Safe on Cam Chat</h3>
              <Text>
                Add interests to meet more like-minded people to increase your chances of meeting new friends and reduce
                the randomness of chat connections.
              </Text>
              <Text>Leave “Safe Search” turned on and match with filtered random video users.</Text>
              <Text>
                Camgo anonymous chat does not request personal information. We recommend that you do not reveal any
                identifiable details about yourself in the chat room.
              </Text>
              <Text>Keep your face visible at all times while using the random chat.</Text>
              <Text>
                If a stranger chat becomes too intense, use the “next” button to leave the cam chat and match with new
                friends quickly.
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container">
            <Box className="sn-img">
              <Image className="img-responsive" src="assets/img/new-friends.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h3>New Friends Are Waiting Right Now</h3>
              <Text>
                Click the start button and instantly enter the free chat app where thousands of potential new friends
                are waiting at this very moment. However, be warned that once you give Camgo a try, hours will feel like
                minutes and other social network platforms may start to feel boring compared to the fast-paced cam chat
                on Camgo!
              </Text>
            </Box>
          </Box>
        </section>
      </main>

      <Footer />
    </Box>
  );
}
