import Head from "next/head";

import { Box, Flex, Image, Text, Button, ListItem, UnorderedList } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="modern-wrapper">
        <section className="sn-square">
          <Box className="container">
            <Box className="sn-content">
              <h1>Why Camgo is the Best Chat App for Making New Friends</h1>
              <UnorderedList>
                <ListItem>
                  <Box className="sncs-img">
                    <Image className="img-responsive" src="../assets/img/interest-based.svg" alt="" />
                  </Box>
                  <Text>
                    <strong>1. Interest-Based Chat</strong> Due to the nature of random chat sites, meeting new people
                    who share your interests is not easy. To solve this issue while maintaining the fun, random nature
                    of video chat, Camgo features an interest-based chat, providing you with the chance to meet people
                    with something in common.
                  </Text>
                </ListItem>
                <ListItem>
                  <Box className="sncs-img">
                    <Image className="img-responsive" src="../assets/img/free-to-use.svg" alt="" />
                  </Box>
                  <Text>
                    <strong>2. Free to Use</strong> Enjoy unlimited, free chat with access to most features without any
                    cost to you! There are no per-connection fees or coins to purchase – just click the start button and
                    meet friends. Even better, your personal information is not required to use the chat app, so you can
                    chat anonymously.
                  </Text>
                </ListItem>
                <ListItem>
                  <Box className="sncs-img">
                    <Image className="img-responsive" src="../assets/img/thousands-users.svg" alt="" />
                  </Box>
                  <Text>
                    <strong>3. Thousands of Users Online</strong> There is always the potential to make new friends and
                    find interesting people to chat with on Camgo. At any given time, you will find thousands of random
                    strangers online chatting about a wide range of subjects. Discover your one in a million connection
                    by inputting interests when entering the chat platform.
                  </Text>
                </ListItem>
                <ListItem>
                  <Box className="sncs-img">
                    <Image className="img-responsive" src="../assets/img/free-chat.svg" alt="" />
                  </Box>
                  <Text>
                    <strong>4. Ad-Free Chat</strong> Don’t you just hate it when you are trying to enjoy something
                    amazing, but flashing ads and video interludes are ruining the experience? Camgo is a clean, focused
                    video chat app where you can flirt, talk, date, and match without interruption or distraction.
                  </Text>
                </ListItem>
              </UnorderedList>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container flex-end">
            <Box className="sn-img lg-img">
              <Image className="img-responsive" src="../assets/img/unique-approach.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h2>Isn’t Camgo Just the Same as Every Other Random Video Chat Site?</h2>
              <Text>
                Absolutely not! While random cam websites have appeared in bulk over the past few years, Camgo has a
                unique approach to video chat. An advanced Safe Search and interest-based chat features are just two
                ways that you can enjoy a better chat experience.
              </Text>
              <Text className="m-none">
                You will also love the slimmed-down the video chat app, designed to create a better and cleaner user
                interface, and allowing you to enjoy meeting random strangers without any distractions. Camgo is all
                about having fun without complications! Learn more
                <strong className="green-txt">
                  <a href="../about/index.htm">about Camgo</a>
                </strong>
                .
              </Text>
            </Box>
          </Box>
        </section>
        <section className="sn-list">
          <Box className="container">
            <Box className="sn-content">
              <h3>Why Else Should I Choose Camgo?</h3>
              <UnorderedList>
                <ListItem>
                  <em className="ci ci-mask"></em>
                  <Text>
                    <strong>Chat anonymously</strong> without revealing any personal information
                  </Text>
                </ListItem>
                <ListItem>
                  <em className="ci ci-friends"></em>
                  <Text>
                    <strong>Meet friends</strong> with similar interests and hobbies
                  </Text>
                </ListItem>
                <ListItem>
                  <em className="ci ci-click"></em>
                  <Text>
                    Begin with just a single click of the <strong>start button</strong>
                  </Text>
                </ListItem>
                <ListItem>
                  <em className="ci ci-connect-1"></em>
                  <Text>
                    Connect instantly with <strong>thousands of people</strong>
                  </Text>
                </ListItem>
                <ListItem>
                  <em className="ci ci-chat"></em>
                  <Text>
                    Chat your way – <strong>text chat</strong> or <strong>video chat</strong>
                  </Text>
                </ListItem>
                <ListItem>
                  <em className="ci ci-cross-circle"></em>
                  <Text>
                    <strong>Unlimited free chat</strong> without any time restrictions
                  </Text>
                </ListItem>
              </UnorderedList>
            </Box>
          </Box>
        </section>
        <section>
          <Box className="container flex-center">
            <Box className="sn-img md-img">
              <Image className="img-responsive" src="../assets/img/safe-search.svg" alt="" />
            </Box>
            <Box className="sn-content">
              <h3>Why is Safe Search so Exciting?</h3>
              <Text>
                Safe Search was pioneered by Camgo and has received extremely positive feedback from users like you
                since it was launched. Automatically turned on when you enter the video chat, Safe Search makes it way
                easier to find genuine friends who want to chat on webcam. Combine it with interest-based chat to
                infinitely increase your chances of seeing new friends and maybe more!
              </Text>
              <Text>
                <strong>Warning!</strong> If you decide to turn off Safe Search, you may connect to random video
                broadcasts that contain NSFW material. Turn off this feature at your own risk!
              </Text>
            </Box>
          </Box>
        </section>
      </main>
      <Footer />
    </Box>
  );
}
